---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: pocket-id-secret
    template:
      data:
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        S3_ACCESS_KEY_ID: cnpg
        S3_SECRET_ACCESS_KEY: "{{ .SEAWEEDFS_S3_SECRET_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: "087a2cca-3142-4871-ad1c-9c32db93811f"
    - find:
        name:
          regexp: "7e8db1f3-71e3-4f35-9442-bcf7b836b51d"
    - find:
        name:
          regexp: "5d9cd59b-1e63-4a49-9a49-fdc0370fdf2c"
