# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:SZbFbXaBgbanGu5zmE8+oUhvEyL1NwKBRd+/pi4/k9HlMwbcKD90Wt36530=,iv:Zugy5G9ZddSsAbUmGCzGfc6PcTFx+PLe5i230cGQ5SM=,tag:mWlYWl51fjB6xp6unEWa8w==,type:str]
    MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:Qrh0It8hHzA=,iv:oeHE7E1Z2sSDFx6VL1SPxHFNYYpNZZE/iWaWEAo+GbY=,tag:81Raht6Wj0YkJWJnQztzEw==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:UAH+dg==,iv:zwLxNLXj9KFRpU2AX5MWlIdfJcBDHMP/sLv0DZUTHBo=,tag:3DXsTfXdrNjuJxBys9X3Vg==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:/Ltn9VgWKNBGpB/rhJsSmlrgwXqny2FhjOWJ9JvgqFUm3t19WfWvnQ==,iv:ipXoHhxWyA0b3W5XEcJRcPKnRUM1RKBGhl8KEIrxcew=,tag:WdDdzkqLniE3z+UkqD2v4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N2lwUVY2aU90NXFVbDlD
            Zk5adjY5N1VHbEFrU3BwUVdEWVJxQW5WWXpZCmdZZHhJUWcybGFpNWdiSTFGcU85
            WndvbVlDT2w3Y2ZhdnBvUGpNRlJxNncKLS0tIGpGN0d4VmcrY3NEYTR0Yi9MS3o0
            R08rOVJWK21nN0ljRFRJWWk2aExyYTQKnO3AuXGE3HdF4jImIuVBu0sebVy5GVlJ
            0fzE6GYPaogg/mf92t0Fc0VfH5MNmRvssSRLo0wKXN3/C0gxV+YR2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:AJLTYa9z5fJOmP2ZvCF8sBva21pfdt5qoo0Kschl/T1ZAKF4mG6zK/lwPppAVNTYUb/yAFq+Nzfj94Vfyr8+/3xAnohjWFtpPs31ZLxAEAqeq30v16aPZhLVdW/TgOXUkXWWFIRmwas4hwF+lGwyCCn6BrnOChyFOFjJIv/aULM=,iv:AxMR1Afc8o8ZILComYlN8ohhdmdwU7i/FQqK+sejyOA=,tag:jHCUgioLRuXrRq0sEkdKjA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
