# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secret
type: Opaque
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:H7GhEQ1q2ZvjdhO2LW3pNwnHjnKi3E0IhvH5lIei3sluatrAKYypwU6Mj8g=,iv:6yZ/q9QFeTNlghuXSWihnhKvnkiZSe1c5QZwgoYl660=,tag:adHmSPv1QxDvTBxlteckjA==,type:str]
    MAXMIND_LICENSE_KEY: ENC[AES256_GCM,data:+X8MepVYfrf/JyT+37FaCOXp85noAvqZNBr0uorH1iXabQtVKapo/A==,iv:zq7obblVifLisiVIR08qXp8Zr1KF81TUtr2AkUDQsOg=,tag:Q1gZ50lI2Y8sfa16Zw+j3A==,type:str]
    S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:XbwwSg==,iv:2X9UVQfkGqwRG0/WhcmkIAUzCTNPWHGoJzsZBIWgpXQ=,tag:1TONavJXoQMv2b1yY6iBIQ==,type:str]
    S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:GsksB46FG2tT3nIaoQAfVoPpZb/Iwbvhz2FthDSbf+cJ9xd7u6B68g==,iv:N4YozPBWZ8dKxv0GbIVedwdGAjGx6QU7YHNkl3HtXW8=,tag:ykNBfJQAOOVIP2APR/MEsQ==,type:str]
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:Es2Lv1Nq3P0m6P4l+ug5zkhmfslmToLyqCyqHXyVQjW7XT6lyuNwl1hLMb/6FLnMu4h/nQd0fPcShO9va4AuYyR6LaB0VQV8GHEWuQppw4fM1bWEo9MugRMk2IRrtt6z9tLy0Agr/Sgvnz4NdQ==,iv:iBwY7hA7fr1gZohzElggVTseCeixGnxckDeW9nNmars=,tag:JYehg1iQ9zLwpzbCe+91rQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VFpqN2x6THZMNHZVbERi
            NmZuNWViMmRtTzAyZ2VhOEFSaHBoakYrTlZBCk1pTHpZd3B1TXVrS3dZWFBRRlAy
            dnZERGs2SVFtNTR2WjY2RmJIQklYUkUKLS0tIGNDYTY4ODdwcU10QkRTY3NpcFR4
            WmRJdHBnUHRISCtwTFFJQ28wMEg2S2sKDWngyb3qeTyTTBDOqH4rtFm1ajhWuPxG
            dDYqSm01a+ehSJoXNbA2sEBCRYENKzXTpQGQGPMt5xQOnYSHytNkGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T17:05:33Z"
    mac: ENC[AES256_GCM,data:dNtfQPw1uF0+hAFuwoH2vguRt+agI8qEfKabkDDFxSTyr0O8/Aq2Udg+b6cy+/LhcZCQMXb7iPuNjcHZ5elXdFr8UHdTmdotC7Psofhn8p+wW1gEGI1YD97MG7H1nXSPJ6EgSnaNlgOUoXb7TYmjgOByYmeATCSFbShEh09U7Ok=,iv:sTTJZSQLAZXJj4Utp52N7iaHhcVLXTBSArCWG7OMMgc=,tag:zT5Sc/BCdpIZA7KJ/vfM8Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
