# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:zPiM76ncbY9Qs3HQuEjc+BOfZ2eEqg6LTCxAn12iJWCpYnpYHINxYHBqxwOxU4KQU3cXCtHRTpjm8vm9Ghtvvx85Kamz/SO1x/g0NVZeVSSfCy48UwTiTVgtWM7bo/FAvGeBaVAiOX291ozFBnXJkOh4rCtN3lBWKw9eHwRhGrA0,iv:v3ITo26SV7umC2AFS5fk70u/eG7pcI3sSIp2ACbg7lI=,tag:IKThGCImJ6NDyC52kjFjDg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:y5xE7L8g53MHU54k8fsda1F83GczfOTl32qV5yMQNI4=,iv:prBDC+NLgVmm/opj2K6Dxrouly18nMbqmrC9m2Y0+GI=,tag:QU/B3mTN1P5/8uTOYueqEQ==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:/DkcOEvLaOG08LEDY7f8SFd1GTThcCaM46BtOrWw53VJFLP0bkvr1a5EWV/Xb+evePDthVMrAGcjqhQvpEvGVQ==,iv:cQFj4HEX5f9pMxo37VwysoLNCJK1Tyw/wOjGt2G770c=,tag:kPr3oUYDk8+Xl2sc0137HQ==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RhIgzA==,iv:89wxeRdiLKOVvWV2LfBOjkEoA9WM+ACbC+ZZazMHEwg=,tag:j7d6N8hc+npidFJlcHNCqg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IZuR3xhGr9pr6uRW7fuGzw+GARCNgNKoP5xZefpXvggAFLW9SrTwyg==,iv:8aekQ2seQsUeDsmt/s4eZxU1H7j0nJPwceNvzY+17hc=,tag:qBG1gv4FbNN7Frx8MkyHog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiLzQxZFFHeFczOXJsMERi
            SW9Wdm90My95VWxQTkxOemxIQTJXQmM0bEg0CmJ3YWpKY3lPdTZYdG5qN2NWWk5S
            SUV6WkFuWFJRelcvOTBnTGlOWkZ6ZzAKLS0tIDRvREppeHFXSDhRdFpMS0psV0kx
            T3hwdjhvQXVkRUppK24vb0hibEZUNm8KwGn+uqtskBXsD4o25KhgI1TG6mGtK3P6
            hABHv9cjwR19EOxs6fJZH7YD34dZhOeCQl2oHj33HlCqVCHp5Vr1+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:18:42Z"
    mac: ENC[AES256_GCM,data:Z0iuK8jrZAChjOATL399cJL84YGyPZKLAVDL6fDAtGmrnC8GBUSjsQmR2tP/Syw6ipWaLdX6dVoDnOHQbsckZ7gpNTzdLsvgPIl78A7Qewnrts88Uj/ZGuc/zBcL4xZw+Dcbpc+Ud21q/CsQ/urarY+etYgeBWzFpxGlUKjuOoU=,iv:xFpc2f9wH7L6XNbH1qjoEZw2B+rKxUjBngXmW50Z97c=,tag:ky0F8svNbkVw+vI7epByfw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
