---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vaultwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.1337.pet/api
      identityURL: https://vault.1337.pet/identity
      organizationID: "76cb6e80-15c7-4fb8-8a11-e7489a28c045"
      auth:
        secretRef:
          credentials:
            name: vaultwarden-secret
            namespace: external-secrets
            key: token
