# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kestra-credentials
type: Opaque
stringData:
    credentials.yml: ENC[AES256_GCM,data:lx4Icx7Eg0dGL1doI7lHEn/8L7YSlfu4UULG0j/IOzjfQ3/xOWrDCqBq9+k63KHS2Xc9O1IntEjsEa1xhxMAitCRUWIfa1os/Ecc3KxCuiL/Nd60PlBp1o9ucP+1XYLysN9JudRtatWE7Af4mJocEM4ANfqMRyCwstOKgj/C7NVo/w/Q/CX7Gx52BFtSOU2iwy7WX6w2E1912UrEK4evU6Ke8gX9wiJQR0Oy2yjU3Nzel5KPcPxcbEHuCsbPVhO2QxA8LObQzN5THUT1u3Uu3QOfWFxz8R2uWoRhrQ3eNt5Puj64PIDkIKeG11Y4OiI53tseVX9GM/zQDibxjMdt+XWpB7OwjNBe15zKD3zAb/wJUCRdoaWTyEGb7ar9Aa631vT7Qny0yc/Y+AObPQR6QYwHDSYOgNYK7SadblT0wxql1FdnTOdYQ7OiiZu8keRxbHxVXupiH30MBnSRhoiCzdzT6+RCK2FXUmUqBeg7O5oX2P0dKdpGVHbrLHvbezo+RRZolKXNch+BwYsverjsVbSWY75DCpQ5atSkBoSdHAszUWHVK+dNf3a0Bo8niZNQQMFTyACtfV5VKMWGEK9Vq6QI42kddqqxsRUHp19aSRRzvNLkUyfDKGocrLAmHQ==,iv:9xiYIcPsMmQD84V8jbZ/MOy2f35d7ZRZk+Y/l12OJzA=,tag:GYCphxr6eYctc2mAy3eEyQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dkxCS1M0Q3JwbzUyTkln
            TzdnOUFRMFNLdjV6RStoSUZrVTFjYVh6VGxzCjhXWlJpM24xay92Mjd6WmdsNDZ6
            aFdqSWZ2SlVrVVJma05yNm1DZDB4UVEKLS0tIDh2WjNHMEoxeUZpbGF0VmNlTjNX
            eG12SkdKck50bGg0SVNNVDJzV0lHZU0KUMJheDpaaMPN9dboxGmR1dW375BnRAE9
            yK5/bqx2mb7G4HDGeq7XqnxhrX+SbYZsvOlSy4rr0awEtxKvQIAbnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T19:42:38Z"
    mac: ENC[AES256_GCM,data:Wr1spB9BCIC3HQG2OzOWK3HSElfcj2xHIIGsAea0Jdo7gxPPEyKQ+Ym4qovzO8ROXkIJiGl3OzRRShkeghBJfSJU8VilvYn1PSospsT7e7CQKRHg6BIBWy8TUoN9m6flb5f1AWUE/StTStBT/TrelnbcJJ31XonZn6VH/jsjW6M=,iv:jWgZkdDoAQXSTe326WcCQSef1LfcTvkPkWHyLwPV+Qk=,tag:3elmoULwK8vnaGTe+MG1ow==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
