---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: qbittorrent-secret
    template:
      data:
        WIREGUARD_PRIVATE_KEY: "{{ .WIREGUARD_PRIVATE_KEY }}"
  dataFrom:
    - find:
        name:
          regexp: "21e526ca-a7d5-48b5-9f51-0b72d3c132e6"
