# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:aE9BPLtcIJU=,iv:Br0P9wgAKWT5evSizYAu1SPgGg5GqZwbFpkaQ0wjYMA=,tag:DgIH6R8ZQoSpJCMBHc9KdA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNUVEZkNzSUhqcUk3dkV0
            THJ6YU9lT3prWmJCU2VtbzJIWWFSelhEZTBBCjA2Mm1jMGZYaTlnSWVtOEFnYmtW
            UnlLUjdKTUo2RWY3ZFVDQStJeDJ1WkkKLS0tIDU5Z0UvTGR4cnJ5RnpMWFZoRnRR
            aEx1cDJrcW4veE0xTllmQVNXYVE2YWsKRKbUg5BLoCAZYaHjfNP/GszKS7C7r4MY
            CwrxOVRvR7v0Sy14EkGuL6RSZDqrppZa2Ca2ar+sHlck1sPbLPOMqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:YhBog0jHkyYqTyKUmU9kqGfaVpeaXsYfo6902hteqJisCpXOfKIG9Q2USnqp7IKyA6mgHdX0S/h/GFeGkQEgJm3xWB9imKy36FmSKwALJjlcvYBh3uTFImra5WTOTvkUtAGOqxB+z6IstXfjFnLeE/b1GDSC/D1g0ju6aU1xdVw=,iv:JedVfSiJtChPhGbsIh5epmCPdKf0/Yh32G6+WBuOoeE=,tag:2nH8dEjP8vwj+iW85ieZtg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
