---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: kopiur-repository-secret
  dataFrom:
    - find:
        name:
          regexp: "2b7e4258-bbf3-4bea-a864-1ab1ab26d7ee"
