# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
type: Opaque
stringData:
    GOOGLE_DRIVE_CLIENT_ID: ENC[AES256_GCM,data:8uM9vXtk/GEOu29YJ7X8ThBAUOQvWmboDlO85gL6QSZVuBdN+FpVdjdGt0/Qy/gxPGvjdeOc8cBcV+qA+WW1ytZQQC9dzmw=,iv:FsdcmI5wCzHUmFRHft95D8JF+qDCopKb51pBJlVJGyg=,tag:iSlwmuzIuo6ONFrCPyxk+Q==,type:str]
    GOOGLE_DRIVE_CLIENT_SECRET: ENC[AES256_GCM,data:hnt3rt+VGdwb+g2+0BKbWY6hvc6t8676+02LDZ7049o1MH8=,iv:p9ViubxWJgL9R/DATWuFiinKQX4AbHgESOL3n0vlQY8=,tag:FBqBfZr8anxw+g+oMXfanQ==,type:str]
    GOOGLE_DRIVE_REFRESH_TOKEN: ENC[AES256_GCM,data:kVslqNnkMfLEqo9gViUJh0lmvRKrRSLip9SrVNVFVXDRH0fMIL3ZtDTYc2ypTsPuXsrp6Nw/TRrnY8ACzAoRGL2SOuz5fV9JKGn6DjRyZkSaF3lt36fhRnYNa/vye+XrgziskaFHNQ==,iv:cvy9Tnf/oGIIPSDLSqm7iXD5XHBTodXObSYk99adblw=,tag:eFMWLgZd9gqLlD0nYAalKg==,type:str]
    GOOGLE_DRIVE_FOLDER_ID: ENC[AES256_GCM,data:Kcm5rg8gYd3cqI3pBKRVSoSdl+X3LTzn1N2VOMSCcLRD,iv:Sk9wwFVlUpkfvARXbCjYL77LhTPm2kAXPe0epgCOx54=,tag:kMMV793OWDzPpFnTtDadCA==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:OY0jswNg4wsPQ0uYlnfLMOwEQxizmpyYSxPyoajFJ60=,iv:MQDrOuuQ5A9l/fVms+SzFm7iNIGMqgMQsjVduQequak=,tag:GPsBEXc/4aRBVoDYFD59zA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCYW1lb3YxTDZ1bnJSVjRK
            Q29Qc1pKK3hoNW5qN0RPVURWeXNuZngvdXhZCjhnN3hxR1Z4TnJhTEllaVpHbjcw
            b1VzRHU0WFAxYmozNjNSdEgrNmJxZk0KLS0tIHQ3bFBxbG8xUW03NXQ0V25tYVVp
            RHgxNGRBOGVHd0dYWWdKOVN3S1czZlkKKX7UjOXmlmH4HVU3Lksewm9sKTcUzDSX
            dbm5sus1Bag/WFS+NkOnTNcefHIJj1dqj6mFjjCNmWAX6P4CBJ6pOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:CahuSmnwwE4Xd4laD9HHGDSKcwfRLxRJMl5cxbzOMvCR8aZGu/w0bidkpZ3zW9NRegaJTwDqNfrGSC5sYndeJuraJaERgrSnqJVmWDLL04pn5ILqJtojHAjWnfRns5/FCmQ4tyUN9Qaom6onTyqFXtWzcmAqyStQPYQ0vyGJ28k=,iv:gSDZ+Gt2bUpnx+vDBKE93fj/oJ+yAFDMYJtM9r/7M34=,tag:cCRWSRgE6TyjUFhSXLyzIQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
