apiVersion: v1
kind: Secret
metadata:
    name: kopiur-repository-secret
    namespace: kopiur-system
type: Opaque
stringData:
    KOPIA_RCLONE_CONFIG: ENC[AES256_GCM,data:BURUrBL3s7jnmSBgl2nFyBKMJ2pLw3fGD0nvbuVFLhuZhU975i49X0j8oW6QtbMq4U395nSimTDXrKkFbBWM8YFMXo2EWH0G84pagSKN27CG0pOBgLE0pn+Uy9RatIhbMykv4uPtPchBOyslRvCGRtk3DI8OJaHOu21CPvoIdbX0CFoFgtpD3umncbluhhWzrjnhc7ogenT6mRYorcsaULIO4NHFn5x7bPvvQIP8a1cocrXoTtCRuZVhgVXpb7Kjz97XjgSwumJwxpgWHD5ovtbMkwy7mmUxwGAFQ2ahd9hSBocjX2TRLA/YzT8cQ9/nVZ66fQGtqMtRFpRK/Uy9oRFZlA/1f7CtMNPLVyMAZMfGnNpFYNKor6xi0JV/nzR5+baMeMBbDIKdI7pif8b+xIvDbS8NmPPCItkOvnU8gcp+09Ou3CCp1wTpZCTXQocHjFYJqmh/yL3R9L4euSDkmV6SeGKPX+ov72BiqQ6xdmU+ZZkTr3yQNXcR5SeGmjfi2zV7v3sfzqU2vIbUn/DYahaij4TB4z2U6GPfnUJF21ZDW9xQzqOK+Wc82Ic9xeRKjoKyBhzhmsXHPoLnR5uupkxqJoQf7Giw7/RA4XL2ge9++7csysI9T1hCxYvKB0GgroYI/Wkvn1p3Ic9fu3jfFkOGeCHY9SmSG+jdOOCZLYn+prvDnAXSoKNv/Lsbb2S2HgGasyDBOfEjswBsjI5l8/08MOZKW9jq9j06eUJ4AovyT17ziA8DM3bculV3EeZrjGfdmd4ynbFz2Me9RhyFtDKy1TKauQBGblcBWMFDXSwSftOr2Mpa8AB/b93ZfLWN5rs8dU5YMKyNX8niFJvhowRppn3wogx4MdrRwYXyJoX17P0holTjh76CjlyUJueMki4=,iv:efiZecPiY820b1/KLCT/p42A0qczkQG54sdUwGjFlfE=,tag:iOJTpQcn+VKdm8UqOlfeMw==,type:str]
    KOPIA_PASSWORD: ENC[AES256_GCM,data:oYM7Ou32pYF1Ij3KzUa8i1w6uoK8NyQmz6mg+7+G814=,iv:+KQSdIohHM0X5SoQnrSkE8NLmLLp+oMNwsOI4rhv4T4=,tag:ToqsHMOuSOHl3UzDOKNzag==,type:str]
    GOOGLE_DRIVE_FOLDER_ID: ENC[AES256_GCM,data:sX/5LafStaL4G+/r0aklpYi3TikDe7CWoWW1D9m/kzxd,iv:5r7DiGzT5qWTs2/8ur5HmV4ojF07aSgiMewLXskZ6+Y=,tag:mT9t/KwNHTtTyoym79uInQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Ynp3eURMSHM5TUxvZU1D
            RjkrdGdpTzQ2cHphSjhEU1hwUnBENDJyU1ZzClNkM25qcCtWN3c5OUlrZzhyd3Qy
            RWdLSytFeWJidUE3Y0JqRVdmMUhkaDAKLS0tIEZscmcyaDNzcFFkU01xTVB4QUYx
            bE1rKzZzMUxUYzY4OThMYWVOdlJpNmsKnDOge7/9sz2tBrdMxyS+iGKvV1SoAPjK
            0yFEg/62SJ1hBY1V2gmPPSra/0NNVG6p64ain0REtO0Da8YCVYiTbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T01:09:41Z"
    mac: ENC[AES256_GCM,data:EkFXzqgAt9AF621IxfDEJc1Ok6h3idusakPpvfMqPZ4FScDPxEgjLtAaeDYPB0JeHElZqQO9KW5pCE5WCbyLCN3KESOtrzz5sWtPJhkFc+0kfsV8VpgGgHStwyXxBgo3Rd2WKMNba9ZDfW0E5l0onv/CrWdZIs5gX0D2u5k+qH4=,iv:6Rot/ZemJ1ikI9c+j67jhsYbRhpwH7iOqsmnUm+26R8=,tag:mru4aQFopTE78n7w9TiwSA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
