---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  chartRef:
    kind: OCIRepository
    name: victoria-logs
  interval: 1h
  values:
    global:
      image:
        registry: quay.io
    dashboards:
      enabled: true
      grafanaOperator:
        enabled: true
    server:
      fullnameOverride: victoria-logs
      persistentVolume:
        enabled: true
        existingClaim: victoria-logs-nvme
      # Min supported is 24h; ~1.5 days matches Prometheus.
      retentionPeriod: 36h
      retentionDiskSpaceUsage: "5"
      resources:
        requests:
          cpu: 25m
          memory: 192Mi
        limits:
          memory: 512Mi
      route:
        enabled: true
        hostnames:
          - vlogs.1337.pet
        parentRefs:
          - name: envoy-internal
            namespace: network
      serviceMonitor:
        enabled: false
