# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:FKAXOccxpEwDbpqXokb6uM/VFSoJEWuqornns8ZefnIarTuvWpXQo6QBNHB62wqFRpQpCGM=,iv:F4JkDto7QulUyeO5GpVfv2csmqSbZoE/NtjRX9rgy/0=,tag:b2TZADKsOh1fKsyq9pPINQ==,type:str]
    CF_ZONE_ID: ENC[AES256_GCM,data:jCDjx/5RdtB8LQJzDPoaXpxeo7SON1DzJ+Kbher0mso=,iv:jCGBt0QQHXrTXfct4k99rfl5xbTNpe+ztUnU/x0VFKE=,tag:lFhZUIC4nNlG5qwVtH0wZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZTVqYU5VOXZWaVloUTdl
            dnBZOENKZjhhZXZUZTNZTzZSRkUzRXBud0NnCi9HZElhV2FrNzZtNDJMbTdPempN
            eWVDeXRXMlVqLzNVb0hXandqd05QTjgKLS0tIGJjbW8vZE9rSFZZbmp6YTYwaHJk
            YUlvSVVYM3dlb1BsOFZaNVVHUzhTaDQKj6uC6ONjxeIac5UQFhi1qpF5c3Lo+BHj
            aBr4LYozgYbbwBnxL8UKDACaygZD5qIhLXvcjVbIGwAmCffJRp3s8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:BXskyEga0R5NqhP+qD6OghgVOQctwp/NveG3SS92yEPJyMMtg4aWMCBzXt4+YbMlbXM4AqV7t9zTBmRc7MqUiFFoX8NMfs7oqIBhVQbC9SzlATginow/fzCxGM57Sqy7bouOVVwGOad5TQB3+ycYWWpVg1855XC/SgFB+oZapjA=,iv:UsUr2d7O2/RTxoWkMB3cAny+PN/FdrQ+t0iZH70Ly2M=,tag:SmlRiM1xZFWRXfWl/PXByg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
