# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: github-status-token-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ZYmCYF6eFqxcOfoMU4qdgON3cIvngwRW7dUI8gODilEOe7a9rxUbyRyC1r4c9OvL5lsvcbSZIVg4LB6S1BXrE7U03Nm1gRzR5tFQuc+ueai3aiIZmSpG4pgjv0og,iv:JaYjW9oVHcI7Q62E88JFyvEMcPT9UcbueCkPG9pCIJI=,tag:jBRT4F5M0Il2PEdK44LcAQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYkdTTEFaeFdxVXV1bURQ
            aExwUlJlaDVxOENjTFFvTnBjdW5udGIzeFVvCmNnSHFIRWZFR09vQkpLakhxTXc0
            cFBUak5JZFJlSHNOWEJPSkNUR3lPeWsKLS0tIFJlVElZODgrOS9zUjFGb1ZKbEVC
            UUhNejg5NDRqWi9zSVNtdUR2ME5jUmMKYmTH/5pZnmpho2v/zSoND7BJTD82qT2f
            JGsqe5CDgepb8H6oeM+/4NrV22TOpuSDoRTtjvLkI90pC9hY7o1UmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T10:18:30Z"
    mac: ENC[AES256_GCM,data:J2ECcDGjw+3jQCL0T8t5Zglxp40pa51Ku0XQnYv8/RMGLz5Yxn38f26jqpsL2Zo1latWWUnA8Y5tWYJ0MyvfaoEXCVHjahSWgb7oy5aL6mqgMmNWeMHf8sFff5mzka43Nu0aXF/MsK6ZadIvClzzNrK6XCld25PIvkNgoDCQo+Q=,iv:/7vWhQTvXujePf50aX3uUatVq5favDIFpAwmq9wzyEo=,tag:r12KAVA5sdY7ccHKjVuL5g==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
