# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: github-status-token-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:2kkLa8CRthe534ky0X4CEM7ra98poF1oHDDwD1Gn/DELU7p7LnEkEb/6x5bDDzvGdek3O/qiALOwa9qUUkBqGIm0UjNK9MtV4hwFf3rXQAwBa6ovPxBr79MO0YVV,iv:LHazZ38c9aMeDmahtY0Q8bFld8FiKSCYpfw1wPwq3PA=,tag:Slmxu0pqlCaSOf0O8UZvjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYkdTTEFaeFdxVXV1bURQ
            aExwUlJlaDVxOENjTFFvTnBjdW5udGIzeFVvCmNnSHFIRWZFR09vQkpLakhxTXc0
            cFBUak5JZFJlSHNOWEJPSkNUR3lPeWsKLS0tIFJlVElZODgrOS9zUjFGb1ZKbEVC
            UUhNejg5NDRqWi9zSVNtdUR2ME5jUmMKYmTH/5pZnmpho2v/zSoND7BJTD82qT2f
            JGsqe5CDgepb8H6oeM+/4NrV22TOpuSDoRTtjvLkI90pC9hY7o1UmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:OmH3zkMgfek60Z9/NwIm76w8XrsR8zsb8kXORXagCEKDwcooewvBgYoapRLAzun98tMWTddMl81+WsHt6m5boq8N2PStw1xCFe+1B/QzYoWmN9dZRCfWjkdLA+54+Ih8B49hJckMcgGx3bC7+HVArSaA294cv8ZOqsXH8aQ2eAs=,iv:/M6oU+S5+TmGSA90QDEnW9bqHB95z9LJ/EcTwUmTci0=,tag:7nCkB+XCzzmHCusoXdfIHw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
