---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-webhook-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: konflate-webhook-token-secret
    template:
      data:
        KONFLATE_WEBHOOK_SECRET: "{{ .KONFLATE_WEBHOOK_SECRET }}"
        KONFLATE_APP_CLIENT_ID: "{{ .GITHUB_APP_CLIENT_ID }}"
        KONFLATE_APP_PRIVATE_KEY: "{{ .GITHUB_APP_PRIVATE_KEY | b64dec }}"
  dataFrom:
    - find:
        name:
          regexp: "7e03883f-725f-4a12-8748-e41904beb7bd"
    - find:
        name:
          regexp: "4f949134-7b37-41ba-bb64-7d3f4f0aeaf8"
