---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: konflate
spec:
  chartRef:
    kind: OCIRepository
    name: konflate
  interval: 1h
  values:
    config:
      repo: github://kriakiku/homelab.infra
      statusChecks: true
      prComments: true
      publicUrl: https://{{ .Release.Name }}.1337.pet
      mcp: true
      verifyImages: true
    secret:
      existingSecret: konflate-webhook-token-secret
    httpRoute:
      enabled: true
      annotations:
        gatus.home-operations.com/endpoint: |-
          conditions: ["[STATUS] == 200"]
      parentRefs:
        - name: envoy-external
          namespace: network
      hostnames:
        - "{{ .Release.Name }}.1337.pet"
    monitoring:
      serviceMonitor:
        enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 384Mi
