---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-operations-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: home-operations-runner-secret
    template:
      data:
        github_app_id: "{{ .GITHUB_APP_ID }}"
        github_app_installation_id: "{{ .GITHUB_APP_INSTALLATION_ID }}"
        github_app_private_key: "{{ .GITHUB_APP_PRIVATE_KEY | b64dec }}"
  dataFrom:
    - find:
        name:
          regexp: "4f949134-7b37-41ba-bb64-7d3f4f0aeaf8"
