# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: flux-operator-proxy-secret
type: Opaque
stringData:
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:o6Ndxnts3uRw3vtAF2TFEMjgz0VOz+dCfAfWu1Bezq4=,iv:1Szw/TeueqeRbUSv50mA+QVow4MbGoPgIlzmEtILXtk=,tag:Sz1LSqZEx9XS7ssKz5d2Nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWTdmbGN0aFZuYzJHcGFn
            azB3OW9ESld6NHlod0xWOGNXcXc1elBtY2c4Cmo5R0ZuSHRsR0ZJZzQ0QnVtRXR3
            SlBmRGwxR05XcEhWZmtqOTJjaWh4QW8KLS0tIHpDT0t3eXZXSk83aUxrMk5Wclk1
            MnhHY29rbzJVUTlZTlRjNlNESi9kbTgKRNWsFIDJHp+6NoO04mGvislB0MokIOQ+
            ekgpDZtvf8vgPGMNXeHS0dwdRrg3vTcHs9Z6bltdjnynFD7dWhZkUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T22:31:29Z"
    mac: ENC[AES256_GCM,data:hg/lveSC1LQ5tT/Nl66Cg7zeAy0YDzAqqQpWQUqc68y/Sk6jTPOoJRIpbeiBC0ckGTcDB20Vvtvkkhcy2IlROERAKAAiXRH0T0RAba/kfU4dwYfBTFh4CqVSja+uWHg+unMJsp3hlAI5xIcHv4jxVC9JLu79gz0gKRN2L34FbRg=,iv:QxmWpQDdkGOhx1scbu5q9gkrV3BZCPbvbXuKYPwOZvs=,tag:dKRTIisAtNfZdrAC9sFYFw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
