# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:pT48ff2lnsA79chBrIfDUEViyWbky5VBaeRoypNtfOnJSIWHuovfWw==,iv:JNWv9cnI0S77Qn7wFozfaurW0mca9NJ/YJKXlDsdGHI=,tag:D6HBrZOtWAktRUCQR4Vf9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbWY0UDRuRmJDbGVZRzNu
            emJXL0xFbDNYVEdleXoxSEd3LzgwVHZRNEFzCjdIeDM5TUtUU1JjWVljdmNXdlJs
            RkVTczd2RE9ZUG8ycjBMczlJWGVkTDAKLS0tIFREV3BPM1Z6U1g1aytaYnJXK1Q4
            YjM4eDFOcy96TjRTa3k1ZGlnK2lTYm8KcD7Nojs5Yvh9c2NtnSDoPfRWFzuhTn0u
            qO8G52rJJUCHcrH/7G669TbI+6KjeZSlzo3OVC2KUu9+mFT+4u0JYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:LnUEt2s/Y6Ai5P1WUiy7PS5wiV9eCqaH/lg/pD3EAPRCNN7ululcKQEgghDxDAW3iKy+nLSv6t4NEUPv7OCW25hCwgTw4So4w70gfzxuHMUaqaG32Hi2QQZQcjLPBZIN9WosDQrwk9zPoTlKiwxgPt2B30R1kTrpXG7BdONVv3g=,iv:xs+XeyExIgszMu/8qFXPZj5HyIJ0YXkCPCSuQcPL7oY=,tag:eVshGxA9bXe7POQp5VFl1Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
