---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool
spec:
  allowFirstLastIPs: "No"
  blocks:
    - cidr: 10.10.4.224/27
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cilium.io/ciliuml2announcementpolicy_v2alpha1.json
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
spec:
  loadBalancerIPs: true
  interfaces:
    - ens18
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: kube-api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: k8s.1337.pet
    lbipam.cilium.io/ips: 10.10.4.225
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  ports:
    - port: 6443
