---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-media-values
data:
  values.yaml: |
    persistence:
      media:
        type: nfs
        server: nfs.1337.pet
        path: /export/hdd/media
        mountOptions:
          - nfsvers=4.2
          - hard
          - noatime
          - rsize=1048576
          - wsize=1048576
          - nconnect=8
        globalMounts:
          - path: /media
