---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nfs-media-values
data:
  values.yaml: |
    persistence:
      media:
        type: custom
        volumeSpec:
          nfs:
            server: nfs.internal.1337.pet
            path: /export/hdd/media
        globalMounts:
          - path: /media
