# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: homarr-secret
type: Opaque
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:1ZPXkxCOIP+bBTMZSs8VSKC+0WuaitzdMSx05vSIIvMqbC1T0OZn1rS3zRgqZS9liNMD+3KCcDPwlD+bXTVSlA==,iv:r98DpecFx0Ten+XohrJTvgI1YJi4TYFf2sAoPzS+37s=,tag:Gu3BZOlVZoaFLBvzU5Pt0Q==,type:str]
    #ENC[AES256_GCM,data:owYaoYRzu4izgXu/mrgWzr/AmRyJSU5hz7y8WaLhaVu/cEjaEL+VazSxKxpCTQZq9nlOBWEssuUkku3+h1tWRGfu6r2HeGBWlxnfpCJk,iv:nwHl0Ezz0Tt1qMCtP6W3ImPn+gWCmD0QuCqlLqN5llM=,tag:JFBGzxQEcfd2uzM5vFC7iA==,type:comment]
    #ENC[AES256_GCM,data:YpN2zTu3N71t54ZQlZ4P5ByxUOLgrQhc6z+x1zP+pD0sXQODfXXlLXdWWHxJyM9mXAeqJxQq+emv180QtgCgO2LynQ==,iv:YTbsKsywlAhM0NTe/njjrIUnPeORNIcUHHdARmHJErI=,tag:pTSn4rlg0bA2C6+BEK5Kxw==,type:comment]
    HOMARR_API_KEY: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NHJxWFo2ZWVnWktFbTlu
            NWFpaEJTZnE5K3MzUnZTeHhiS2NmSDhjZTJjCmJRMTdWK0E4dlBLa3FGMWs1V1NH
            RHhtV2Q3enQrcFllUTg4RGhVbE9GNTgKLS0tIDcyaVhxS05TalJWMTdVKzdiaVRF
            ZkFteEd2U2pYb2xFUkFJSjhWa0VNWEkKz+N4exOu7uVjz75J9KhYUdpCrUK7lhxy
            aj+QvQK0SQY4EUhaRKM62Jtl+JWzkId5iNHsA1amPr3R7LX6tgBFvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T14:21:07Z"
    mac: ENC[AES256_GCM,data:bV5h6XFiZSBmC3YoIaPXNqLSMMmLhkSaxE8jSTKucvlmu2KiYt4l5AHx6bJXarO/m4qZNDtXiTp4D/geA+ArwldU21bGBkZSJ5qIOGAyTbeumbek9V9Z+gNOxfgrEvOipW6R0VLoNxhbKJlmfY1soCX+R0yma0JBw/dS7WSuW1M=,iv:pwWAlyR/D0umtQRq1WjvwM5mBo1G9fSrAakwrVma61U=,tag:woMFqEeMoWW9D1KeB5ztYQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
