# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: homarr-secret
type: Opaque
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:1ZPXkxCOIP+bBTMZSs8VSKC+0WuaitzdMSx05vSIIvMqbC1T0OZn1rS3zRgqZS9liNMD+3KCcDPwlD+bXTVSlA==,iv:r98DpecFx0Ten+XohrJTvgI1YJi4TYFf2sAoPzS+37s=,tag:Gu3BZOlVZoaFLBvzU5Pt0Q==,type:str]
    #ENC[AES256_GCM,data:owYaoYRzu4izgXu/mrgWzr/AmRyJSU5hz7y8WaLhaVu/cEjaEL+VazSxKxpCTQZq9nlOBWEssuUkku3+h1tWRGfu6r2HeGBWlxnfpCJk,iv:nwHl0Ezz0Tt1qMCtP6W3ImPn+gWCmD0QuCqlLqN5llM=,tag:JFBGzxQEcfd2uzM5vFC7iA==,type:comment]
    #ENC[AES256_GCM,data:YpN2zTu3N71t54ZQlZ4P5ByxUOLgrQhc6z+x1zP+pD0sXQODfXXlLXdWWHxJyM9mXAeqJxQq+emv180QtgCgO2LynQ==,iv:YTbsKsywlAhM0NTe/njjrIUnPeORNIcUHHdARmHJErI=,tag:pTSn4rlg0bA2C6+BEK5Kxw==,type:comment]
    HOMARR_API_KEY: ENC[AES256_GCM,data:4FYhquC7D3Hbn15I/F1DnRgDdM7y92S9XW1XeHIibgX8jTgg4xJiS37ZhmJBKD4MzpMJSBuMmHbcY0OI4vp2Uy1FORPlvH+l5SAeTcWKGitFQcMU294hh3gPh+ekbIFIWIeGd0go2ie9xDUeAeeGlR1whB7dvIDAqSxk2VTFet4ep2ZFuyArrnNp3z1STMCufNdgyB+Dh+uT,iv:xCYQpFJwd9/4n2LwoiivjkBUByGqZWUQXR8WMhlEQbU=,tag:JC4f+mwK1UfP9ZGVL6OV9w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NHJxWFo2ZWVnWktFbTlu
            NWFpaEJTZnE5K3MzUnZTeHhiS2NmSDhjZTJjCmJRMTdWK0E4dlBLa3FGMWs1V1NH
            RHhtV2Q3enQrcFllUTg4RGhVbE9GNTgKLS0tIDcyaVhxS05TalJWMTdVKzdiaVRF
            ZkFteEd2U2pYb2xFUkFJSjhWa0VNWEkKz+N4exOu7uVjz75J9KhYUdpCrUK7lhxy
            aj+QvQK0SQY4EUhaRKM62Jtl+JWzkId5iNHsA1amPr3R7LX6tgBFvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:00:05Z"
    mac: ENC[AES256_GCM,data:llQuQbwJ98xqGcc/1bXIhY8X5A40HFGkB8LAE8jv+kBONJqNcelpZhEJvksO4yGCD7mRfdOa0ZRbSpZw61PRIHq1xhEvE+LytYqxOTGIZ1OrJJfCKWouFrwmzxAHkOB1LBfMjsY6QKE9pubyPFILknn+hkzi0s9IueeoJNmSYpI=,iv:phDmRRYfIf7lEJ49adzeGPN2tkIKXpks1EKsef6Nxdk=,tag:h+b/C/ejkeFsZmnbF8Ie1w==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
