---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backup

components:
  - ../../components/alerts
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./restic-backup/ks.yaml
  - ./restic-documents/ks.yaml
  - ./timemachine/ks.yaml
  # Temporary: PhotoPrism powered down. Uncomment to restore.
  # - ./photoprism/ks.yaml
