# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:DPPYBqFX9zO+2fHKp8/xR+i+Fbv3A38h51vE1RqeAt9MYEznJto7Px6+iNc=,iv:xrFO4CQekV08Hb5uKYcczgT867e83h6zQQyGh0F0pXQ=,tag:HZK5R6w4RjQOzjQfm4wDmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNUVEZkNzSUhqcUk3dkV0
            THJ6YU9lT3prWmJCU2VtbzJIWWFSelhEZTBBCjA2Mm1jMGZYaTlnSWVtOEFnYmtW
            UnlLUjdKTUo2RWY3ZFVDQStJeDJ1WkkKLS0tIDU5Z0UvTGR4cnJ5RnpMWFZoRnRR
            aEx1cDJrcW4veE0xTllmQVNXYVE2YWsKRKbUg5BLoCAZYaHjfNP/GszKS7C7r4MY
            CwrxOVRvR7v0Sy14EkGuL6RSZDqrppZa2Ca2ar+sHlck1sPbLPOMqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T16:38:11Z"
    mac: ENC[AES256_GCM,data:DyhuqYKaG0XK4fkOct0famcohX6PlLa92PqMevkfuBXHx89BQ2iRY27jX3gmIIFLgfq3fA48s4vSfwMPbdH6zMI+7SN3b6hF9Y+quuRQTQTlT5LCozujEgy/8UYpGEIOH6DLPr8NKLDI4fmYk5rZdN1HhDYNMYeN0fbOXr4j+ZE=,iv:LunYtOfTFsooQGMM2J8T/B6iqBXCzPtEZNJEATwrrGE=,tag:n4aKrsCOT04vn5bOVsrkGg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
