# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: mailarchiver-secret
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:jexDATqytLsPMbwxGhcOY3uApJUC5kfxT47Sjk4ZiKI=,iv:Y9fArFIgsBqEWvUCn0SHvZ/KWSquUEvmTFWmPYaZgpw=,tag:mnO/5W7+5xT8GfQR+ZBPaQ==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:NgDI45fqR6Gc4pRQXhKNCJQYf/L/fVLv,iv:cJlKAOL/k7zwdyNWg0/mQKxX1ug3LcJOkjlWY76imfQ=,tag:IhWhTtei1LfuZ8+fGZt+LA==,type:str]
    DB_CONNECTION_STRING: ENC[AES256_GCM,data:hprpaGFm8eRig/QijpgN9B8RonnblIeg22yRwceBCyqedaDS3iQUEeLWy+m07lcBzIPshyBqnNim04oCHZjQjUzMuuzw61DusIMjS1o1M5I1jP/vz7H/C4yDXFsgw9nnITQdv2Uiq7bPIIhbKgeY+Oyoioi4tZdGmNpYKgFaePWwK6N8dIapBKG7l0ImGKZWcNCz,iv:cvm0sOmk8Fqa8vRssCDud6i//6SsjxZ6EjJ/JnOOUzM=,tag:pUPrhjLqdgb/B5fFKFoFRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMG1TYkdDWE5GOHhlVEdi
            WFR2ZUJYQnc1Nm5hbkFZZjdyNGtXV2gxUFM0Cm9IcTF6MTcrNkI0ZGdtZnF2M0J6
            eUhKeXoxVzhoeFFiLzVwaHdnd0ZNSHMKLS0tIFdaME8yUFR6NFhLMmhLTDF2cHpv
            dTB6bFd4QWNnaks5cEZtaDNEMVBxNmsK/vvMLSVnfbp//kugzK/WV0E1S57on9f2
            rkr5D0NFRMVLYHvZLzytIUHaWiiX5UdWvHc6jO2ubvbF2XHi6T225Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:38:30Z"
    mac: ENC[AES256_GCM,data:Pe5IADsVPq42R6y4b0E6G7S9jvERnybvlqu3AamUoWrveYQ1zqH4w493/897KexW9UfY4+YBkvbE1zKsIhoeg4aoMwyzufp/4WK2CHPKD6RBtA6cjP6Rl80GKzaWGWRdSBoVVHDzw7NDqkbBQje7xBhRSZyPL1Zae6V0o9bcmas=,iv:M2bhw3YjmdqGpkwup4KIQmf5UDB8GZcXMBAac4XJjpA=,tag:+1MyA8QNrRgl797BRSq7CQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
