---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.1/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: wallos
spec:
  friendlyName: Wallos
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.1/dist/schemas/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: wallos
spec:
  name: Wallos
  clientID: wallos
  pkceEnabled: true
  skipConsent: true
  callbackUrls:
    - https://wallos.1337.pet/oauth2/callback
  logo:
    nameOverride: wallos
  allowedUserGroups:
    - name: wallos
  secret:
    name: wallos-oidc-credentials
    keys:
      clientID: client_id
      clientSecret: client_secret
      issuerUrl: issuer_url
      discoveryUrl: discovery_url
