---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: alertmanager-secret
    template:
      data:
        BUDDY_HEARTBEAT_TOKEN: "{{ .BUDDY_HEARTBEAT_TOKEN }}"
        BUDDY_HEARTBEAT_URL: "https://status.1337.pet/api/v1/endpoints/buddy_heartbeat/external?success=true"
        GOTIFY_TOKEN: "{{ .GOTIFY_ALERTMANAGER_TOKEN }}"
  dataFrom:
    - find:
        name: "5eb5a8fe-cd4a-46b5-99e1-0ffa54224ed3"
    - find:
        name: "004f7a5c-3c0e-49cf-a21a-d2d3219b26e7"
