# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
type: Opaque
stringData:
    BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:drTHsDsnTRQ=,iv:WwNdAjbtcRo5nH3CuU+6az51/U3faejTzf7S4TZJ0i8=,tag:abTyqN6lWb/6jEvn7utlMg==,type:str]
    BUDDY_HEARTBEAT_URL: ENC[AES256_GCM,data:qEdKKpSQWUs5TUO4yky5vr3bB+cc/OoEenGh/Lvzr3H/RDNeqgcYlTpBhmHtiiHm3I7bBJ1rkCOUm3WM6eizr08sTd0Z3sUv7hLm+OVA,iv:4L/IVbrvOp4phJZdiJOrhYB/m4GMKfaW7ezXAbu0eSY=,tag:Us7VLMtyC4ST9EW6YjCCJg==,type:str]
    GOTIFY_TOKEN: ENC[AES256_GCM,data:FY7+LOEPz2g=,iv:Hu/qGXjxN8DOgxm8s1iTb28ReACQhJzVp3X6UcQynjg=,tag:I1o8fn8NbF+ML5TF+E4Z3Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTU9jdVVwM3JSazVQMVNH
            dENFQmdlelczQmtkb01kQnRBU0JQZmxUYjBBCkY2MlVSbS9HK3NjTzE3ckxUeTVq
            QTdlVCtkSHpyMUZIR1pFdGtaWEUwQUUKLS0tIDlJbTBuL2l1R05xOUhObEw1RE1l
            SkpUc1lmRmJDN2EwRTNWUDR5MmVrcEkKpfSc2ggFaus3yXrRjmFJwmC43PoXh5ON
            ZkywXth04wN4BBZ763Ybw9KH4c1lb+0MhsWFcjxFWFmCz2vQy6zp3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:IzGarbc+P6ngDtAvFvJbD1iSa7mlPvBzSRXVWfD4DlbTtVF6QFKvvPCxVuOmBb4VLF6bgoGW7xeTyB8xcZwMupnOdTAvFTygQ4xFWfoFOeeQVA5rYvqwdpxQmWXTGZtcWs9kobot9mUmbhcEeEBJMGwUva7FS3GuPdnPhYl03lc=,iv:c5salnloB6/CR//3DgqabuymeBg9dqpyaUjE7epO3OE=,tag:3HQObLf4byBwQQsI/kZ3jw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
