# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
type: Opaque
stringData:
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:dma+no8DgBEE1S70MFvwhA5bMjP6n/fNZes=,iv:lrlW4OgTeQl53FtT1hT6T9HE3ZokAJtvAeS6KpM1QV0=,tag:WAxjp3Hv5BrEJ0GTNWiWag==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:5/OEaozFL48tmFx+iVNOOCXe1ks96uA=,iv:WVVbkBGw6RuAL5KjCv0MLNNjfVRvGsjIRX7E3Gd9L8M=,tag:nMTFm8vtQUftbdWMtpBSRQ==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:vlEDrFt2kWWkZv0YlKeDHu8liLjQXQexff335bcrc6kL3SBwTfJz6AhrzLotpZt04lPdNrj/t1E19kyZLinTaA==,iv:NENtwijcrqtep7BZzbAUIqiVFrUOOJl3pf7J8Vk8WIU=,tag:7HuQNQA88hrKG6O/wkWm2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByK0ZvcW84STRveEQ3RHVk
            alJUQXFUV2RLY0k2U1dBME94NVBHR0xFTjJVCjVLcGJWeU1od1pXZlhvQlVxYXN0
            VWQ1OVh5NVlmUG9SeVRqMmUxMmM0ZTgKLS0tIHhBYS9zRVFiWUY2ZThSWVB0Mjl2
            c0o3T080Yi9LTGJpTU5IVm9rU09YY00KIK2U6oTL6R8ihxztF96FaZ0xFuTrdxII
            Fm5P8x0nhC6JhjjssAN9XcMKhh2YUed0Tkaq7Pyd9I/LuF1LPOIHow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:v9azNASAtxR2/j4b6ddMSdNgjk/SlDUTyNkb2Sh0bNVxm5mOGFJI4aP+inrKDWRBU5wlKlDuHIh8+YC7jHzq2t7LALRifalOSg3eAhQg1YxHIt/fXIW6PHTgAMeGT7KAMDlLkKuEFMEdtnXMwjUaQ3pifMOqI7SS5bcpi//XSBM=,iv:3Q2ti+3S0fGH8ZshZai212/6RtBUtCIs/EW83BJKVV4=,tag:WepK17AwyOolbYEmY/hwBg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
