# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: one-api-secret
type: Opaque
stringData:
    SQL_DSN: ENC[AES256_GCM,data:V5LkCbsntngDOmujSdFt6p4xBY2/8rHbMHMgJ/ayla/QOzn7auXqZAO1UfLjUz1bhqmt5RIHThhlEA64piankgnAXJvyGvgXiMQcLvh4+UiVmsc3JIuo8zTT/+pDbwxPIroj0A0=,iv:8r1lrz+RV9mRnirccbPRtFg2cElu8ZZh1GSa5pdM/uw=,tag:fPj3hP2WIccyq78N7gwaTA==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:j+wMUWR08J5Wg+umFXtEPCvxV0/kfLMztyH/thL4TBKKtkm+Dtt+fRGNxbvsn1ShkewEnCOktFIMc9k1mR5/Bw==,iv:5BO39PW8CAfxob8v4nRkYbSLDyyeldl4gmbdZOJjdCA=,tag:A9SiJGaYA0t20stGqI/yJA==,type:str]
    INITIAL_ROOT_TOKEN: ENC[AES256_GCM,data:R1UFDunqvh74CFjvFHwpf3OERUyPI652tF0fcAE5gxmzruoMmiyBbCtLBw==,iv:bClxWzsYy1YyQW+MmWrIapWh17rA0aPv7NVrnkAqreQ=,tag:Op2x0FywiiDQ+1y7r7ekOw==,type:str]
    INITIAL_ROOT_ACCESS_TOKEN: ENC[AES256_GCM,data:q+jdtGZ7+k+mXdfGJQ+4wA23FvxJJuYhQJ9wSgdSgsYHkwrBZkT5FNOr+g==,iv:G4HJzT61ARjJUMDFYd34KNdRbrzL1oK0H7fbngc4FxA=,tag:emXEch5auDJGQONMtQ8mMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VGE5cStaU0hDT29sYjNK
            bXhNaENKTWRhcVZTYXNqYXNzZ2ZLa21GZkdRCkNCcHFVZnFSN1VHSnRFL1p3bjZB
            d25NSWpkTzRUOElZSjdxUzFsMXZObDgKLS0tIDE0K2EwdDFLK3RKd21JelVoSEVr
            VU5ENytKSWVzOENINTNzd3paa3dqQkUKjwTSu33A/A2g7H5IBhQ687bBiIyuAL/i
            KhY+LyCsJpmM4XuiDleciaqEcU+ABrrsHAmcrHBmcD7oqdFDHPCevA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T19:54:55Z"
    mac: ENC[AES256_GCM,data:BpW+QCo1U+XO/XL/1K7YP0RD6WvdEw0mTVS0JWLcTVjgVCyCuOzQ18rTfX+k6wEuBhqA4LscPRyxR8WJ+j/eY/Lk/MOT3e7iwbq55ANgPfaGLjcWyhhKUPR1lhr88Q9n/KHrLLXtYLa/jJ7uuJKadSQXVThUzhscINs0KQqy9Cw=,iv:0g2rndnYyynxuF7XpCSEFTpOL1H21lkwD5P+H0LLGR0=,tag:Kv9Oo5L8/ZATiOtZFcuWqA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
