# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
type: Opaque
stringData:
    CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:wbyV3gzxn3/W0eR+EEwcKcXIugAP3ZehEsATNxlhrrAymvtE,iv:oZ4TcHuwtKgRNUDws/zCz5flitWIbQsCnJYQl7mLDcM=,tag:SIapcw4fStn/Q4MQjoOAvw==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:NKgiOQ+4okxoTC4V0u+LycucGW/7Uz1kDFdub6fHLRRaSf3MS0rf5S11HnZWQ3r8n4HGtyiC9eoxFyC+HuGfti9Z78ftZBTCrqaDH2OO1Mqw103t+Zu6sXvKFlAiGKzaPQNZEjKTyZzGP5TqXBeRy9FH0bxwDvq846FvZrHgrw5ezD/zeXAX9kDN7hv/oyxPJQlUP3wRAZQ5fnqRXwXv4i30pkx697a1P8omdO31MzTslKnPwNqH3Q==,iv:c5E/5kU2Zs2w2t/H2kBq5pdhPliTeZxhQzYTMv/jnPk=,tag:YiYrlHRhc9ckT+YePiv3eQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UGM0dUdWMEsyWm96UUMv
            WDYyVHlPVW9odXc0UzNvVFY4OWVrQlJidEY4Cm1BN25FZDV2V0wwRGp6TjdJQk9U
            Qjcxd1g2dVV2UDZnT2M3eEpWK2s5MG8KLS0tIHlVZEt5N0hoYnoxaXlHYVhvRE1u
            MjNiK0FaVjQweDBEanlIbjk5US9acVUKEn+f1gwYkJXR1cxiM3KzPhmmXpYJCJ4B
            wshMzfRbPdhUqJO+NKmmytiwfSftwwYD3ia31wJyq7eDkPBnnhMHtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:fAvtBUXE1b+VZjRQY9Vqu2zAUeOfOYlaqm0o7LlaXIMBMTH2v2KLYRf6IHXPbdfs5JRoIVqfex2h9dtTlytaqIca0aq+cD2ti39Eui9LV//JbDBxfQrjtBg09YmIbSBKu2cE+vTfHxbfbo84SvKsxGl7ViwrGO4HhGYlFlogOEY=,iv:gcyufeGHHk4fA20uUFtKwxBNZAeQ1De/bF4J+fXjI9U=,tag:6mM2Z671cKUFN4c9kNunsA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
