# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: photoprism-secret
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:ya2D/rx8sCAPDa1P5zaCz/3Pe65DIV/7S8EmoD085R4=,iv:YEOGt7Q3l36szFjwNQbZ7R+2gEGcuNjIMpmziqJReNU=,tag:i0Zelv/AIRE/wlwF5VBO0g==,type:str]
    MARIADB_PASSWORD: ENC[AES256_GCM,data:F875Ogi25QZIAn4R7NZNXQrx2iWarKLL2r7qHuGL6XU=,iv:vD0qRo7zyAi4MTqHj42EwdLqXV71zOsF9R0UwB9HNmw=,tag:dwK1ByNd38XYwxkS6Np8Zg==,type:str]
    PHOTOPRISM_DATABASE_PASSWORD: ENC[AES256_GCM,data:yatejKMpYEVRYOSBPnQ34DLO/kGP9cnKeZhIVOhfiAg=,iv:3QwoZPacYA9V/U0wkbdcQIBnfIRfX05gTFv9BxI5JQ0=,tag:64UQgvrsX/8TQty7GPxi6A==,type:str]
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:3dT62VX2uAxrhFPAIz/Tq13jLDp2nUFs,iv:7fpfunNZYeyLi861e2uQIv+1p5Hc5fMthcAQLFwq16Q=,tag:oGZ+WcHqDUviIZu02DAEuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNkRWMTZZUTZoaDNvdFVD
            NjBPRU9OWEZubWowWVdCTFRLUlR2ZXJzOWtnCnhpR2hUcnBIS29qcG9YZVN3NGFo
            UXV0cDRMQk5UL2V0UFAxZ1kzc1c5d2MKLS0tIHJIcWE0YzEvdWRIaE1PMTdxNFp2
            WnM4VS9BWlJDK1BacXc2M0I3cmdreGcKeyVaTVGoMiqRUUx2UiM0NpT++JlPZFY1
            Gd8gQy0YrSBWDF0pKfkt0RqZodx06VWduvX1aSGqxwrN4UM6iWBcTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T20:32:43Z"
    mac: ENC[AES256_GCM,data:FRzyDoqhtlJ3ubmJwfudHzNIPtJnd/PFF54j3Z23kLDn7cgkMh5cuYE1Ng/DEGl2qKrbPjiXYWPhMA+HnyMjaEDq72jE0NTD+Z2GNWIMmpf23PLKJjvcaF30fZ4ORYW8r8AF0Pi+rw0hkwwUXvDCDk3QmAJzGdVKz6EeazBMKrs=,iv:hK4QCUB4l4sjJMUKn5rLuqma2UK8UqhlW2GycVfKMv0=,tag:5sKhkEtvu5adPDw9uvD+sw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
