# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: photoprism-secret
type: Opaque
stringData:
    PHOTOPRISM_DATABASE_PASSWORD: ENC[AES256_GCM,data:aIC8uohFbUHOUw7H1omOpAoEZtEeUNoThxz1e7yaccAY7R/UZ7p9afzLjh0=,iv:xiqaqs0guyFqfDLJFrB7zTxIPnussIzB9GDV7MrRKic=,tag:a6wywuQ40eGUjnnXJfitBQ==,type:str]
    PHOTOPRISM_ADMIN_PASSWORD: ENC[AES256_GCM,data:U4c/11+x6rTQdBvXQ0rBSe6kC75oW/y/,iv:w6ow03d7Y8vqFTDintE9bBrG5D0JlVKQpIbZ0sf9GLs=,tag:hvP7MtERDv5CBS9Cpf8IhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3JvZmJKaEhJMVovVk9C
            VklQWW1FOWxab3dlcS9Ednh4Qms1SE1TS2xNCkhnNGFrcjVSN1lSRlZ3RW5mWTR6
            cFRLZ01DSFE1T0FNN2F1cVBHZ1JNWlEKLS0tIEQ5dGpxVUEvaFhtT1hxVTdWUGQw
            d2dKSlkvQ0g1K1ZPL0tUaHdEc0MzTmcKNpFArTTRDljVO/oVqqb4STKzk3HwoETA
            1DT+v1Nx4fPtjM2jjqN0BH3NuffvXaZft5eokF1N944p0sKN3C19rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T21:55:59Z"
    mac: ENC[AES256_GCM,data:VrAtKeKrO2wzyrAaVtV/R2Nu1185kn8zxKrKf9L1dYMVZYDP1zJSvjW2oBhU13cAEl2thl2GwA0W2qYeAbt1IsKsEtHcJd/P6EnDMAOyz29tAqZcGxo9aLxDTnVxPFsi0nW65OLmmMyfmJdwAOGvfuMr+n2LmrBDB/NRkWR7Wkc=,iv:jj1bKKhDhME23ma0dAbpd1ulfS4WaRYpH9ttY9yY7cE=,tag:3RXUbtFp7jigqXTocGBRew==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
