# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:krprfZNBTSyU7T48jbnLvWM0fDys0fZfhM06VILJxSI=,iv:4UWlHoSXY0Rl8VJor5zmLc8chhhgTEuT7tz93qyLWnU=,tag:yefyY0qqzfXsRLDEoo0ONQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:6gNUTs3biLEHLpJVilvfQMRc1jwnY8O8hEnHKkogKryXy7pvvES/AIAQ9g==,iv:ucw4DX+lr8HwQZFg2BbedOEut0AsSS0W80RjQmW8geg=,tag:5+YenTUVXzS3CDPQ/eMAFg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:pWlfl3Y=,iv:NJT5sk2jmrxEfnPHchFHu8A4ynWCyhZNAZUfV2iMHpU=,tag:mwEOs3kJGPS8dsmeOQxndg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:zJWwQK5RH7z0RFEVkxsjX5BiDt6sbg==,iv:0qPkaAQO9q/LG7/GegGu29Pa/baKmojizofoU3u0fYY=,tag:FSmtretClGQFyVkkLY3gKw==,type:str]
    PAPERLESS_FILENAME_FORMAT: ENC[AES256_GCM,data:ZZX+E7FtYrQoqsGuX8k4gd7gx4yaCid+P+HCSN0YHfaX2k/Gn6iGaH/syTunlcPCShA=,iv:LBXVbI8JS/UYU3ptTqsoklvAhhFU1PRHc1Ejhm8zFnI=,tag:D5+fL9wTOlJ2jLD4g8GQ0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSVlqajBpOHNuMkRic0ZL
            aUJmZ2ZJa2JBc0NFTXBmeExjYjd6aWVCS0c0Cmg3QmF0MTBKNWpTZjFCYkVKWjZs
            eDdrdlExQnJ4clpONjRlNjFkTzEwZlUKLS0tIDVoUWsrRFpHMWpXQUtyUG81SzFi
            N1JlUEk4Q2NvNFdLVGNMVW16WDBiTlUKIxP/PUYJOykUdcDZ7B36NRrKG87TBz+N
            wFUtSyBB3s506xUJW3LZz8avi+DphwxShHNXK+TPZZ3nfBM4JUm4ow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:02:02Z"
    mac: ENC[AES256_GCM,data:IEw1sOJlmvjdDdeaIwQHrf1bD/8j2ytIWJhydpV17nshx6T9MjLqOlvuqGH3ELdjP3IRDp2GldzYZrorNEHtzKrAJ5GZDQbH6PKrgEgKULjjFLBnKt6UA5n7mPn4jrcrf/3pPL1wIBGT1/1euX2Hbb4aWeWkhxzH7XT7X3twgA8=,iv:M1ro7Rz9b6vp2UOF4J5/V/lJ+9Z3fylrevvWYycFnvs=,tag:ay9w89WEI4dULk8z/SSTuQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
