# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: wallos-proxy-secret
type: Opaque
stringData:
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:fnUwP2gs3iOWDNT/8ORdyVM/IqTQEh3++/whHAgr824=,iv:g6vY4T3qe1rEWhDfmNJzkBlAM19QN2btWl3Jqalkxyk=,tag:Qgt5/X+NuG0ejBJRktwLTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dUY5eWlUc3llSVgzOTdp
            dVp0Ky9KaXJKQWhxZjNBb21ndVQvMFNKUTFjClIveWhVMGl4amZrenI1U3hhTDg2
            R2pGWEZuOFh4OE1JVFJNNTUzem1vNTgKLS0tIFRqMWNzQ2ZDTUxPRkF1WnY0VWhi
            WUpQckYrTDlFcVRyZU5SRFdIbDU4TGsKMmY0LhrfRUXX2j4F2zSxprtS469FsGqf
            bAy5PkoFtoLY3WfxismuhV9Y/MPk3ne0Iwn3Xn5QnhyVzioWfdPjUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T15:54:38Z"
    mac: ENC[AES256_GCM,data:wKCVwDGA5Aar0uQCg94Mrf2NIg1MeNWglEWnW0eBI1Y24gfQb+dsZIsi21K/pUroXo5PFwYGKpONHnZDNQxK2uMD+xLN3IRnna57IBqxmv/NEynBIuxMnE7VwEsjWHB/jyhv4YTiNXWr6+elqpTJ4xtETt8gmWC/GigSVzKVCHI=,iv:Va9uctc2WolBBW36WVu+em1p9BCOTtav71XYrMh3Ea8=,tag:R7QdtvCBZofcFUUIolDCuw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
