---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: unifi-dns-secret
  dataFrom:
    - find:
        name: "8f35b39c-acc5-4d0f-bcbf-417bb87e0310"
