# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
type: Opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:8TdgpDt5Lj0=,iv:H6+PR19wXcch7FyY56CEAevWW9VmrfGpJctL9kL9zHE=,tag:WNRbIqd/t0VDtsPHycHtMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNklxZ09BRVY3UDhQVndR
            ZGlWaHZMaUpUOUlFTS9kL1RjdVJaMVB2c1ZzCmVuMTJaTTV3WWRSK2NYUUc2bVZS
            WnFsNzlDR2gxTEtiTnpPbndDdW5FVU0KLS0tIDB5eVpFbzFLQmlYSlRQcDNOMDJG
            MDQ1WkdQYmx6d2tBK2hocTJ0ak84eFEK1HTH4I+s3X53GbxmcJVcEtIuuvZbYUxZ
            R2sv2jnBifhyOlx6L1CL8YdMyCu2LVp7D4zbANBgK71GCutT4hiatg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:DoIeyrJH/g6Y3XhfUfnOzlLmg9tK1g/CRMKANrXsH3mzPTxufrnj1/YiDquY5KZ1CurtHOa5OHGjOShBu24jIxb+o3W34H/IKNXEpEvh2xkqMBqlDvD6m1H54Xmjp39bq2dT8gtnax4HSJQyiSsmiuzVS20UqOzj/BwvLcy3oyk=,iv:fnOqlOZDtbez4mwFJcoUkQoLFEUWpnf39XHCoiqiSNU=,tag:hhfaiMco+3+efT5dM+M16w==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
