# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: unifi-dns-secret
type: Opaque
stringData:
    UNIFI_API_KEY: ENC[AES256_GCM,data:tnskB0R5leonck4/n4AoiGyRMJByNZ+rcon82Cvnv8U=,iv:mRd8WaAJFMoSLvMppA7RaHM3fo5Pwh+PjoS3JWxJP88=,tag:pyB9XmwnDk9UsJENywARbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNklxZ09BRVY3UDhQVndR
            ZGlWaHZMaUpUOUlFTS9kL1RjdVJaMVB2c1ZzCmVuMTJaTTV3WWRSK2NYUUc2bVZS
            WnFsNzlDR2gxTEtiTnpPbndDdW5FVU0KLS0tIDB5eVpFbzFLQmlYSlRQcDNOMDJG
            MDQ1WkdQYmx6d2tBK2hocTJ0ak84eFEK1HTH4I+s3X53GbxmcJVcEtIuuvZbYUxZ
            R2sv2jnBifhyOlx6L1CL8YdMyCu2LVp7D4zbANBgK71GCutT4hiatg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T16:47:26Z"
    mac: ENC[AES256_GCM,data:lx1Klzdr2Yu1eDDt+86UMJbtautBg07tM0NGjpshFtH/M7XnDZigEBOfJvxa6R8eO/qAtcHb9VUh9kc/ESgGMI/GaVWGRLyGdN/r+R/ZxWWacA+LgmiIqtwn2aQ1OtXXXh5Vyqx6QKtrVrFZ2eNa2HL0GFjp/3BH1wxc/UaH1KI=,iv:AcF8z+TUI159ZWmYGapvDQTUuH0TTasOAFSZwyjf1X8=,tag:lT9iXcEcBebx234KXGVLHw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
