# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
type: Opaque
stringData:
    QUI__SESSION_SECRET: ENC[AES256_GCM,data:+egmd0gPgkKx+zJqMjF919o5iFl/u+4pigry02QT5rvpVvIB744lX2BodzwqPEUzL8Muo1qT94QKs6It+9bbMRwHzPqdnvQi3+t1WMMvhmOGEUYj9DAa4AYb2kWUm6IA5VuUFq/eCLIiW64m5KV2h4+rIEOQs4/TWRNoebuQEE0=,iv:wHPVjf1yhc5PS5aJ7wOgsNG2+BJZl/nmf9LpiAHxq1M=,tag:9ufkTSpUWnuc3mGwTn9b3g==,type:str]
    QUI__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Ys0nbROULqw=,iv:viovKWJKhBUBW2saBxhmVBMzUSqEI4qeSdbIqe1E+c4=,tag:8OdfwmdVWvOefzoTWu4mSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUzhnaHlDRFRBcURZTzJl
            SDVNcnVzWTdsYTk4YXREY0VVUGt4MVFUWnlVCmJKRWtlUktnZjRKenMrTHRlZW8x
            N3o0b0JIOFR4MENCTmNBMy92UjBVUmsKLS0tIGE5NXRWeUVNZnpQVWttQmZHbGdm
            aU1ucjFHVzJiTWl6cG5GMzZPNUVsNzgK2tRQ+vdJqeLKTlfqHw9uUZlmBCts8vTf
            qdGfo0eaWeXbp2aqRsQfus5cA0IMPlsBUCJ2LI8bifSwX6ORNtAlOA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:qff5Cxysjz4W288yHj65VOiIQjOf+EA9VP+hgpsCkHsgtnMG2dyBAX2XpJPmJlJZg6KgIgHOK4puDleypy50mQ6N5khgNZW5XAw8Uj3uBSIICIspG1cQEffJC+m1xIdpZyxcBLLdMyKm0WntQ4PA1y0pYxdam6QMRk9+2LFIJ+4=,iv:GECFWRLBdKw66NpoQ0Bce0Hwk1AolNbnLWoBIOj/dDE=,tag:7ieSnGeki0LEDNfKed/VNQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
