# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
type: Opaque
stringData:
    QUI__SESSION_SECRET: ENC[AES256_GCM,data:VgJPaEeEO2MC6rVPQVIOjxS/bOtzOXXhyTpK4CxuTTHja72HJ3VkiXr3aERVc4I0SBJDqa4GT0+hVqCKTt9VcwEh5j9XQXtxdf2NYafogvqneBKMRXGoi0PaU1ajVJwdpuFM7n6ltP9i2SeNn9Wz/m8XHPfd5z6weZRXdmBVj08=,iv:1vH7DaSXoACRcIo7Zd4H1UPtzCEezner1u3aXmjjqng=,tag:f0zBTUGUyImJvn61mVt90A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNVdCOU9xVFU5aVN4ZjQx
            azRqRzczMFdKMHE4ZTZEZXA0Z2hqWGdGTGt3Cm9rZEQ0c0kxcDQ3cG1hc25HSjVC
            RVFKTVhHRkVHTHh0OEhpQ1Q5NDB1cFEKLS0tIHZUZ2VRK1NGOEY3N293b1ZSWHlU
            RCtaVnplSlVDS05xYXJwWjh0U1prZU0KFve6J3WTmeMxQq28mu2Wm6q8N9VPGN4Q
            Mmf7+ttceworgxfSQ6gfn8EEICGK0l0SL0fKgLsczEx+9EK4jm2gDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:02:02Z"
    mac: ENC[AES256_GCM,data:Izz4Y5u+BlCmEXprSxkVVW4XPB9CMPt84wdFXcaULqVyfg4XjFB9RGGGWT6LvFve4lk3BJGYkpvZZd2m93RFuQBUdut0SzX5zXF1iG842m5nWaQzIUMi79LphdPLUzA5Vy+a9lfFbkH4hww/mCyVRIxMtMXm8+KjSoEMPOQde50=,iv:dP8+msb39quuDw0OMfA4b1yNXOy4Q2TOGXL6V4MYRCk=,tag:rkMUAPVvJdeOKSxuuB1kPA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
