---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-issuer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: cloudflare-issuer-secret
  dataFrom:
    - find:
        name: "895122d2-2d9c-481e-903a-ea457c2f31db"
