# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-issuer-secret
type: Opaque
stringData:
    CLOUDFLARE_DNS_TOKEN: ENC[AES256_GCM,data:7POvieQN5KFca8w87THwWOFb9VDQ3J1M8lbGOq6lKTiWNkGFg7HO7cZFKEQ8CE/UXHCPbwA=,iv:pMnwfq/++qz568iU8FLQv7ubZ8+pgXQsaT9rZxagMG4=,tag:c0DCPLbv4qzJU2VfPmJa+g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVmVsYmlyVnd0Zys4Nkwy
            aWZqVFZSaExoaXZMdFk0OGQ0THBzTDJWNW1VCmJidlhGcm1vVkxaSER5TVVWYXRX
            Q044SjI5WEY5djN1WjZLaXJ4cVdqbTAKLS0tIDFOUUdNWlVxeDFGSVFFRUZmNXNN
            RGVydVN4RVlRVkdnL01YS3ZqL2ptY0EKnZWOuJ33pHDOTHRILhxE3eQM0CF8SXEt
            xkD33x5WJcL7w/3IhAxiSjzP/sSIKebqDSxcmv5kszyBINgHHLMyUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:Fs65Au2BP7oZkSNcxGZfIIVzZZtTQ5oFMRSuK/3lkduCQiONl2iC8vGyQiJL3aPwDeQ6EWxD0+MP6CemtSnUf2UjEOzPkoZbstR7zWrsF7sxLxOwj7NxTf+AGej22EfG3RzNy3Swr0RLfFYP+R2XJo8AcHSetGuWlEtC3lTFpj0=,iv:WIoF8ik6kliZrbMQ4toa66e7t+HCAUrmhOcf+BrA7Zs=,tag:WFS4r3RXHRfkfSAEj0AFvQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
