---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./main-db-owner-secret.sops.yaml
  - ./main-db-pocketid-secret.sops.yaml
  - ./main-db-gatus-secret.sops.yaml
  - ./main-db-paperless-secret.sops.yaml
  - ./main-db-linkwarden-secret.sops.yaml
  - ./main-db-vaultwarden-secret.sops.yaml
  - ./main-db-mailarchiver-secret.sops.yaml
  - ./main-db-penpot-secret.sops.yaml
  - ./main-db.yaml
