# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-penpot-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:5xQ1rJNe,iv:jmBfxeyNYzcqHakTQu+6eMPOTouychTYmGbpoK0cJ2M=,tag:bMr+VzwhU3r23uC3srzffA==,type:str]
    password: ENC[AES256_GCM,data:takPNmktsgCHeYonI//iAjjNJNmqTfHzyyY4B9D2zQ0=,iv:3S6ji/+AmRwiQKUxorkcm8UnMc6e3wAyCpJad9NzvrU=,tag:Ca3KMbIFjvDgifQRqZ25VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWFdyUjRBcCtBdjA1V1py
            VHMwVHdpMUtOdWNNTmlwdlcyMllJWU5XMWdnClRZanMxU3dzVkowUlNkRFBjTDc5
            UDN6cHB2cDAvNWZBeUNtV3E2cmZlbzQKLS0tIDh6WGxCVDcwNnYxRmUzSmlWUU1v
            ekdzQ1dtTmRBMnJaa0hocUVzOHZMK28KoUgACyXi3dzqzTT2EQE07AwFLxh73UxD
            S4xzShvnIZjLrSRY4lHWEbu5V51/KIlscmnjApFXPRmb/4KsDnUJdA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T19:26:49Z"
    mac: ENC[AES256_GCM,data:leiZap8Uzl/RLTJ3PCVEg1KUQhmr1qI02wUuTUtnjr8eCEzEGUaDEZvcsGE1AJEr+T6d4pypoD84jhxTq6Q+gh+7iBODAfJRSgo+fYfeYzhdfyDOoDOvW7wbA/+8/IOgEciEpgtMLL3Yt6EPJHoGebK0bkArVt+M7lEwsjLtceA=,iv:IiUH29XPkW4cuciNtq9Druml1OMZb/72bDufgvsVoEM=,tag:1WxUlb+YC1uuLFoym4bPrw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
