# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-mailarchiver-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:PRk7yshHgp3xCR2r,iv:Y6fuGlSR+aYBT4ghuusKrPQ1VMVGrVzaBhdBx4e/hsk=,tag:lkMs9E9S8BlnXtRga0DkzA==,type:str]
    password: ENC[AES256_GCM,data:RG02bLuZJBf09N+ahzftXmSJUwCltILfzTB67txWqZk=,iv:QVq/OCbPFw3zFb0KjgkuJm0AFlO+yr/SCTFDHIKGG+g=,tag:nfYS3516e8au1h/0exAKTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVU5sVjB2MjFndWNUN2RL
            QmhaZjNEN0ZwOFRqcGdYVVZ6enBORjFsTlVJCks1amVLdnp0eTlPa0NWSVVTYXRM
            aHhPeFFCWGpNWEoyd2xXOWNPaG8wN3cKLS0tIDFTbTU2RE5mWWVpTkRNNHVkSGo2
            ZnFVUnZQbTFWaU9MSkRQVkFpbnBDTlkKf9ta7Vz7YB8t86eFhQai1Q9+wJc+/cel
            QZ6ttEpiiKbmbXAJdQk8ryx2TRGtPGzmfzCf83AlPe1l8WPqytQRhg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:37:37Z"
    mac: ENC[AES256_GCM,data:UuDxEQvpPQO60pgkLxncnuxUZTjFSX0V/VCk36eLapij8mgjLeuKAf9b7tK7bHDW9uqyvEqXSBcIYy54nKOmYAVqt7N8LlUoEwz2gV3uS7TSSMeawEa4tJIz1ACXCq72F0+onfQyu5MTvtz4MiHnkd48lJi/ziE2gLXjc6/SSwY=,iv:sJMugyX8Sg9iEanA99asy9FVgwmdLbOgapthJr0IOZY=,tag:7GaWn5GeKtC5RLcZ7YTK8Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
