# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-oneapi-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tOQPgOiB,iv:chje2WPgzqg8zzH4/WuOA6gt2KjaP/340Chpayq2Uts=,tag:gS/VKZIEQZ3bXfJZ1WMfFw==,type:str]
    password: ENC[AES256_GCM,data:iMRH7AhTesCmM1/8W4IXIUYIav7OK6sT5B8wAang09I=,iv:Llb/BENhAjXrccnTN3R7av5Q+jYK5y+i6n3T8mIUBt4=,tag:8URMn9x7s/exSkiX+7IktQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTXoyUUFGRWpGeFVFZkRS
            THFiOXhCK1BydkI2czVzNExzMU45L2hEeG1rCjNVbXVhWkpQY3BUbVBmUjNnYlhV
            THNqQ1doL240NndCN3FLaEdPdVVGalEKLS0tIEVKcVhsVGdobmdkWmVEejIwajVv
            NGhnaGRwY0hsTktaN2VRajlCMUhxS2cKJT33ZOhem4dnm77k2xJKHMWi+ucYD6f3
            RRImbEPa2nIKS4oKgL43+xByGvPmq3OU1yev8CiEskvhtzLA2aUF/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T19:54:55Z"
    mac: ENC[AES256_GCM,data:P73M5F2fZ2Y9Yd+L8z3RKIHcbobaePnDzOevKUPa9MynakSYSpAoKmcJJMduxcpovdTPzXBzhTCL71c/QdwHbXdetXZBy71dCusRPPbtS9g4WnaD69UWEIjzzVi/FZ9hjdpgOq0dccaJ/a/7bb5McphMxHnV0AhQuq1GioHRVYs=,iv:RS2jnJEvdh9pojqcncF/wTHi04+t92aa76HMzrehvO8=,tag:BR5mflp/Dx8LIqP4kWA30w==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
