# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-gatus-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:h/P2IvA=,iv:23FmTYhrRboADKsMsyfK2FJuQ/jIgcRdX92b83qk4zo=,tag:1kImC8n1NeWVNmM9l09Zeg==,type:str]
    password: ENC[AES256_GCM,data:Uv8y7vDH4ZTMRbAFX2TpNrbXT9bC77FiKPyN20Nf1DY=,iv:Z1a2J+hPscSYbGgQDudz6JJdzqZ7MCV8XuvRRHT8mhU=,tag:rnzPDjoWi3efb7N0z3e5hA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcjRLaVVhQ0MrWVc3cm1U
            RCt0STI0UGpLZjNldnI4WFZLdDFPczJINzNFCkxXZkd0Z1diRHJKaFNXeDE2d0pF
            dWcyS2ttMTN0c0dPN1dhclVmcGk2NHMKLS0tIGNJbnQvcE1IbmxkY09CQ29JUmR2
            TjJoN0t4Q0FKakRXQU1IaTd0dEltbmcKP7QWMwbZLJUqPaA9Nm4W4vjXx8wh3u1q
            3mfPWxCAoLUP5DGrvhdskuxGbE2jCerYbdYm8W5FL/gHCSPLrLhzjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T12:21:02Z"
    mac: ENC[AES256_GCM,data:5aV5ztUtw2ZfxYRy79IdtN7lBJ+vAAcTysgDEopPSpui8ItQTEbNQ1rABdJeivSJvp7C+Qs80ykED3cDXJ10NmQ4AmYOPiag6CvvrHFRZNFO5KXtsZeDNJ90YoenaHUPY5XFcY+D9CsxfIX5lUgsy8PNvN7L5LsL6mH0ncJyP/o=,iv:8p/YSvQw+WNGwtPZ/gRBKjoE5QXmAQmlZGG8/XvIug0=,tag:mFoDGEkyR5P0/mPMcsjBMA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
