# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-pocketid-secret
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:qJtmmjA258Q=,iv:TNW7HY/3ivlIX5F093PBC5jY+GiPC2OZHwELzR1YV1U=,tag:4+F91bEgQh7dnBUj+m5ekQ==,type:str]
    password: ENC[AES256_GCM,data:u+PVmOYqFkHlTPLseUtzgn1zCHHTmfh+giI+mSIZfpE=,iv:HysnZko6k5FNAa6CzjMd0gP/1OW3eeMp8LGK5StkHT0=,tag:GUqV7HIx2tqsxA2wPGkhNw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZjRzTWxnV3VjYUpWSFl6
            YnZKVG8vckRpN2d3Z0ZtS3ZXK1luckxoaXowCjFCS2xSZ1pvRE9ldDZxYWZYSURm
            RkNMMGN1Rms1UXVXNTBlbldIdVNsSEEKLS0tIGltZFQ2eEpzU0V6ZkJsQkE5Q2pt
            R09rQjhLK0ZkVzhaYU04ZWo1QzRCWlkKO+C8hTaRiVh0hU6S3fFK5dQ1EtcjJ+zo
            XuFYyBLm/g3Az3PWKbMdB+NoYxj+HPIXTwMQ8B1ZXc4tTP2YrR/Qgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T12:21:02Z"
    mac: ENC[AES256_GCM,data:8kuDDmWdeepX0bjcZ8e32Pk/uHlWU+Yo+9MyA6XfcGY1v7XRuFyD7RJCaq8H0BFJBeeVE7x24KHVsceV6TLHQf8NB0B1uY026SlRCOW7zTy+6x3He26/nM6lz41fErUyAVgDkD8jYLRgsbF6J45Ome4Pa8reaTU/dR0nwR3AEts=,iv:sVPuoHvL8Ca3HTekxIIMtAvfVVnbo2qmyXdoEB8ixZA=,tag:opw+UWAxJWhKo2TOx+WzQA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
