# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-linkwarden-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:OMb76QmZfptb+Q==,iv:1LWnt5tNRVCkmJHEwUM3IvyJ50ZHc6S5abrhApaiwvo=,tag:IpDoMtqIMKbDqwo4avD5sg==,type:str]
    password: ENC[AES256_GCM,data:7UOuedn/FBuMib0lxWhRDf5Q1qPuyDwVrf7gXLwNWww=,iv:ad1a9zpl3cKdSVA3XfeRNfOb2bMgZSCOSFnbLJBGrGY=,tag:FBhnJBykex4pQFJu/2RQRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwK3ZpTFJZLzdERVdDNHJh
            N1JMYWhzVzRUazUrdDBhNW5kZjJqUGZqN3pVClNXcHBOdWtTYlBsYzVxaXgzeE5y
            YTJSY0hXVnY3QXQ4V05GVWpTcTh3VG8KLS0tIDRManFudjdLeGgwR3pNMDZaMWJn
            VlBVcmU5VWphZCtsNW8zd3ZGWkxtSXMKLMhVjBZKMWcWVJDL5Fmpd7PI7SVxfIKC
            8AJE2nLdAJNAi0kTzzqPE1TdnCKwDptj/c6Edng2HIzpC7JqWCN+eg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:17:37Z"
    mac: ENC[AES256_GCM,data:hIwqAesmrMh9KKgYGIcG8xsfT8skLblZ/SkFNXwcJcqz1lY2O/Ahh8TQxUoOPEdIkFb+/X+3Zr2CxevyMp7Fnw0wh6CxH1anLKHHxmy9SSpmu4IQU+r4lwOFw4nB+prAWKmo1zvzCbZJskGnlQiValJma5jgY9oeHgjmGVQZeFI=,iv:01D6ubUl+Rd4D8BM+LreFULd4SX5fCQg0SzHWu/1FcA=,tag:4Dk2sAg+rxG4v70CNYOT+w==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
