# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-vaultwarden-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:EnMjgPuKSU+Pxjc=,iv:o4YFysRgTqCDHAl8tZj96f7MOsGtKQZoyIlLSjFyCzs=,tag:oMyK0YrAaMYcEr6QhDxP8w==,type:str]
    password: ENC[AES256_GCM,data:VI7yoXYXiWQ+YMtj7YdwSvfVERV7ILZgzHzC0O+rOdg=,iv:Wxn9iPxYd9yzssj5Ec77aI075FuDKm7oL7mJWapf7kE=,tag:cDrXcMbLIh3JTKalk6x2Mw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdDY5MlJ3UkFGZVZNbFlD
            VjBMaHg3TXhPVFZwQXZNWmt2STF5SzN5NEhzClFmMXR0UkFJWHVaekJSQk1ZU1lE
            NU1sL0QvVUh2STNJSWJmYVVYNlZWZmMKLS0tICtnWEQ3TmdyVUdkVVNkOU9DeHFN
            ZTRNa3c0RHpjYkNId093MUE2MkcvQm8K1/B+wnJgvOBkk3nAxPAHxBFvm9Hi0fXs
            i7xbm8jtr5kX+cqVX5c3WNJ1hTJBQjcCKhVyhKIryIM7yuKaQpKi3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:17:37Z"
    mac: ENC[AES256_GCM,data:ItbeTPqV6qkD0HV+uqNbgXbA+KHXpOsfV0jjetPLe36RPcSTqLuH0rvhHDTKAMAM+/7WeMXum0vSbEXJ86z/sNF9pURqnHyaFThlWfamHFVkwqbtaKB4qI6EZngnNa5CqiDH0aCKXuHh/b3ZSz+VqtmHNQ4vrq5vsIPL3g7LZME=,iv:7cUH0+ygj814BXV0O7Ym25tbElciNqFK1YvR1JTUmkY=,tag:Mx0TB2Q6DN99VgkY4uahRw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
