# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-owner-secret
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fluHfg==,iv:LqbOm45BksM3NHfYHbe4iqZwOyoXnmbLKIiDZqALjmo=,tag:BRyZVt7uVKldu98WWl3vpA==,type:str]
    password: ENC[AES256_GCM,data:WekerWDFIiDInUdQOA5dDZ0pSGc3giNuZDpKEUe4yek=,iv:9GLExcgj1eJ9aA3QfMHh1wOeZsszJzT23FD64zRm2Yg=,tag:w4rZkGVrbdm/04wrQPS64g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM01pK2dLR2hDZWVaUG9a
            ZGsyNllvRDVvUFFoeUxJVUVTNitVc1VscDNrCnBSa3BTNi9hNjVlOUorZnU0VHVa
            TWo1Y2tEYVdpMG9jaFhpdnBiUmI3OFkKLS0tIHNtSXd5ME5xa2ZyNFNWRFN5U2I5
            ZFNqaEtPV2s0OTVsQ1A3K2NUSk9IZ1EKue21dfbJPFG7Y96exBy1W9oNGTBFKYzf
            Iki6nisPKjqFNl8FuT+SpPOXToSOHX9wOY5SxtECOqR2+ByKAemBZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T12:21:02Z"
    mac: ENC[AES256_GCM,data:mQutKTE3Kgy/iblGUZZmW5KNjE9KmBF6acbkywnrUOCMOi+vjl6pF14LCrWSNOpYYUmOjgzYcifAn+DOv4CYzjBpvdQ7tTySbEAMNifEH8ioghmJVqOjbODu4G4jDWKwM+bRa6dN6Vl8aqBS93x/byQJkRx5otMvZtqpqyLT2LU=,iv:EGes8ufZw67YnhTbwppGvaG+YuTUefqPkghuZ5eg/GQ=,tag:gCncgmmZ7ouZZVW0iK7+ew==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
