# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-kestra-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Z5sZARMH,iv:HZi/DONNcymHnUxfbJpCARjEDO6cvsztk6GJeXE4bYo=,tag:flE/fYqfX6Sk9L9WT5RpyA==,type:str]
    password: ENC[AES256_GCM,data:E2TOdF3KEHHltF0L1IZmynHPa+VXXScWTNsPGPEA59I=,iv:A+3Dkaoxmxbl2U3egD0Ih9LGPp0PH3XYK6TGo6jYxr8=,tag:DoKFDy+/M6LctSaypc5ADg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3YVZoYzBYTENmSll0QU55
            THJDbjUwYlNFck1TbDNkbVFBeEN1M1FLVjBZCjB0alQxbFl6dnRHLzJkWVdBYkJR
            QThSSFZabThqSi9ISzJDVEVNNGZUSmsKLS0tIGkwWU5EYjJjYk9XT2dOY0gzdGZQ
            ajdmem00emo1bEJUWEljMWl3Q055aVUKgYMffT+z9zs1i9L/HbERNUqmyLEPmjmz
            eOLG8AffNujC0rXXMfZv9KcXXDlcpIBA711Gg6v04EZ/TvHRu3+r+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T19:42:38Z"
    mac: ENC[AES256_GCM,data:iXN0Bf9Lz3qU3zNQf6cUojp241fNflVSX/g0+6jiIyleihW3siV4CJel5LrKLVdQROabmA/rTK1t2a0xSBeDZpS/8ygwa7xwfEmuc785FHftOoL8QlcSwT+q8vm9Vxj3N9W35PQ0LDvyBJd2Swtfw6H7D2KtWJeToRH8Fpq5IKc=,iv:UMCBG+1IEh6qaXWZVFtV0Npxr8KAg+iaGRZd4KkLOC4=,tag:v/fJiJkTQpGnNFZ0nW/bcw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
