# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-photoprism-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:maWI93FyQtmp2g==,iv:pz5UOSW3xPIDGtJxiiOIpEtgFg9pBcax8ZuIjrgrvTY=,tag:cgkVdQE60+BuF/FDSWi97A==,type:str]
    password: ENC[AES256_GCM,data:8t+cWMQvbdlpWrvvXzHEtwspJl1U8zy004pPgQNAdBrO9kIiRjmv9SSKZaA=,iv:sUFRYjayZv+qDC8E65l82g3h3KolmOd5xE8DP4QB6NY=,tag:qGaFsrQrWIdNa8Zu1EutIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzejdVK0x2dzV0V3BsVnRE
            cCs0ZGpxODB4Z3VtbkdvakFGZTZBUlk0WkV3CmhaajV0c1lPWXcvekg1K3E4THZL
            U3htREFyUGZ5SUQ1OHNCU2diNzRkRHcKLS0tIGJ0ZmdKY21hNkxBa1MwOTQwdmdl
            UlMvcUF6U3RVa0pDTm1YUzdZd2kwUnMKAllO5KL3HVovSYxEGNR9pQiRq8oChZG6
            0+5Ucbox2rNTxr+zCpW/jGPeBzmCyZnGK+tsnVWdsGA58l2zYS7r1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T21:55:31Z"
    mac: ENC[AES256_GCM,data:5PxX3n0RxezsPS7u+kHtkbkpVLz3F7frYd266xSRgD9kOM+KAjnjRkLBZUFZR9xo/PWYYfi4K/QSxCsTejgsn+Dcwmwfl2OpE6WpjPVYZza0LIz7rRlNh9BKsaKbY+1nyBIJ9A9fayyy7yZEris8CfaAIhUYHD6EzBwYjZggTYo=,iv:t5zct46BSxWKMVHhOMZM2vlWYIB5C0slN98hPisvcak=,tag:GaSv4OjgJaibNWKEmrYMeA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
