# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: main-db-paperless-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:BaIRJllSP10R,iv:Nn6qYV9qwYLA1GLdHcBO5qKjPDuair7RQ98jX4ez1hI=,tag:Vph7NZRdg1o8ooAos3lg+Q==,type:str]
    password: ENC[AES256_GCM,data:ZuQSz4rVIVAYAb/YS4cnslI0gI8O9NlqOxc2PMFSMhQ=,iv:BzQMeqRb6QsLfMGXVHBuBmxDQnwe1FyjtzNZqcglUsc=,tag:ApKZ5OvX2SFNoJ86F+QnjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRWgxNXQ2MFpndEFnWVNT
            WkpMUXZWL0cycXR6OHluYWpMcGpra3BFRFMwCk5lczN6Uit6bmg2OUpjT2hkQk9y
            YW9BYXlPa1hUREF4M3BOQmY2N2tYczgKLS0tIGx2UDFOdlJJaHNEdVovelN5c0FX
            V2x1ZHpmdnREQVBUOUt3aXlMS1pQR00K8euaFx0SAjxi/5TnsyIWNRu92Mga/ot0
            X5ksGtIxOCjEmeoTo7hGORBVyRlVyx5WEGu2NR2MNtIJMXJFTa+rjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T17:22:40Z"
    mac: ENC[AES256_GCM,data:nww8RnH1BWWKJbbS4VEtlaoZLBS1PbYvyEjfQjDwW5TDQC7MYP70K3ag8yKTQqnXPjHI1OgX6ptAbF/sK/NDB6T2SxkNBQyD423B559RWi3MwurkqJVs39KLydq+v3sBZRyPKu3GC4tciEj+3jYPkbcK8lB4I0Mws08H5MBzp1U=,iv:/xjK6dmtC55syDjXAEDPDKZqY4RXWRhUbJfuN8FDRQM=,tag:ogGiB85boyPvAvztp/SAxw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
