# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: homer-proxy-secret
type: Opaque
stringData:
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:8S2aAB2nuSvSIDMG+KeoRQ//s/AP7rC7+9VFBngYvBo=,iv:fS1pDmjD+RUPGhPzHI70/thh5XjFTqqjCyHEx6UIYdc=,tag:vjdkJBbxbtuDVTMu0I3B3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSFlyWW1JNDE5T2RhUElZ
            Q3p6YlUvNTFDUXRIVmNlMU1tZFk0RW1CS0hJClBmV2tUNS8ra0JkVkJLb1h0YWVp
            RGNYYU5LTFJNUWk2WjJBdnJ2aDY0Nm8KLS0tIFJneVdXcitpMWRJV29TUTBYSHBT
            Vnc0S1VCNVpMZC8yWmNITnlJOTNmNVkKea+4Sdjp9D7Fm8opbnNxhmyK5y0z0qd/
            CHq1DhFHID/iPpFMEEDW3QQFNb1IVfFnw8/mAiKskf2pXCJnO+Mmbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T19:12:30Z"
    mac: ENC[AES256_GCM,data:4FA2qMBpG0rRTuVPc4IymrdEP6RPiMKmUXFW5wPA8qsFbAxgy1ziQUk1ZG1yFEX3mwOy2y5/ehL+L2tkypXc20CTUabTNxD9aj0C585nBcX7rrxBCD+BNbW9LNQDvYS/kdJxCqBiP8sUK+qQmM7G1wSUV0SGQgge3IgfMvgZjDw=,iv:jznRcWwPSWPMrv5+FVeJTNaWKL00Nqlx2KtrZilhzoM=,tag:rubBIuZRznNl/rzHFYB0Cg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
