---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus-sidecar
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: gatus-sidecar-secret
  dataFrom:
    - find:
        name:
          regexp: "5eb5a8fe-cd4a-46b5-99e1-0ffa54224ed3"
    - find:
        name:
          regexp: "004f7a5c-3c0e-49cf-a21a-d2d3219b26e7"
