# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: gatus-sidecar-secret
type: Opaque
stringData:
    BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:GtCBsYMd5wE=,iv:XACfUFy6ERf26IqiSvtVBqWdELd4V/s4hMCUnzY4cPs=,tag:nybQ57H9fQJd7cbsbFarFQ==,type:str]
    GOTIFY_ALERTMANAGER_TOKEN: ENC[AES256_GCM,data:YpL5XjD8quE=,iv:6Rn/YFrmxj5qR0yzR5agaCia61gQz2hYIIOv0HJ8fkQ=,tag:sfCYT8inPcCrJLFU6TyLHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VXR1cGwwNDYrbkw1MFNl
            WUczVjgyZENLUHNQUkpmZXhEVkdZMnVLOWtNCmhGaFhwUEo0WkxCRDA2SGszaHps
            SkFxK0lCVkFXVllxbHlnZVVPOHN0VEkKLS0tIHh5NzBrdFBMQVcrakFoOWJzWVRF
            NUN0dTNhT25VMVhQNHd0QWc5VlYzcWMK8tetHcB/OPmrokCli+MDir5ZU/YTH9We
            M4TAMV6ka8LJHCTCFhSHJwE0bsX4QJLKYOreHicXteyYTkgDeHUTnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:DB43KTvuGRFyfgSH3T4sQeYWcm6mkEz5PXCJKZrZuyrNruC4J1QYwrQCZ7pZyiE45pHuPfTRrbT6yOkAjrq/CrQeBgi6kidiehc9kwRox/vGTnWaqq+IND4BrH5b3h6jD+QZfUo72WPFpWRWUKyWxF9G+y8fKK1Os2+zvLSflRs=,iv:zzHhVSy0/7fHXFm0o1s2F6kXTa2zTPgSqkwOnXJv2qk=,tag:Sqr4xiY6a0gtRhTpOoDG0g==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
