# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: gatus-sidecar-secret
type: Opaque
stringData:
    BUDDY_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:3aFZdyEvJ84=,iv:vtqqrltpAoP6S/vBqDpbWQKekS7CDFFjOoPetC+us1s=,tag:iPrmhyHe5cNSg4K/FmielA==,type:str]
    GOTIFY_ALERTMANAGER_TOKEN: ENC[AES256_GCM,data:H6F4Why+cV8=,iv:4Hrp2xmk0hAtEdRQmxU5JhEJsGkzkYyfRQbLN6pZNcw=,tag:konbvp5RaUkgmedy5NExlw==,type:str]
    PG_CONNECTION_STRING: ENC[AES256_GCM,data:3Ibwfn0Scus/dz6csPvcy1mvl3WATdhQurrtwh1uRK4nIskmYTqADpojoILedexcEFpSnm3j8nQC7cJJG865FfLXm64v243jn9W5q9Pq6/CQkhl/rmbUFx9fERlpJc/Ln0G8PbBzyg==,iv:gpJtA5nM0RQU6Y0hNvj7UrWhI8B1hNni5tfxNGk6BcU=,tag:Og5B7Wty08c2gJde8oHBVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOam54aHQvcGdZRVBWWmRk
            TlBYQWVNL2ltWTFrdnpSeGVoN2pReWk5MzNFCkdKWlFHcTVrbVg3MmUvT0V0aWhS
            dWN2TTR1VWpJZ1g3aDFuVm5tSEZJUTQKLS0tIEZrZ1IwWDI3V0ZlVmE2aWZ4cXp5
            RVQ5ZFl2M0pZNWR2dlo4aVpkWkUvL0EKgdepH+wN5nnJkGLqg7+fk+yunWfQfKHN
            d+V5eoQiZA9fyM0x+h7QTgPC053K6cVhf0BfvuonRViyv3PJp5KpcQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T17:05:33Z"
    mac: ENC[AES256_GCM,data:t69z95IaPC2dMO2YW8RjC4l3YzapcjmJ9b8G4HICjHWyg3xhEfhAInVFiV5MEdn7IgXYjGai2QAusQYf6snh1evEFvmnNHb9xYKAar9CRFIjXioYXtt5JJM5aR4BPrHvfnI7u+OI22ySGHfKk1h2WwOKJE89UGZx0YQ422Vk9mE=,iv:RTuV8yy4cM7mHSemdxlp70QUHZv12yD464Lo2kmeick=,tag:z1jau7taktZVXRJy5OjUbQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
