---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: o11y-alertmanager
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
    - nolock
    - hard
    - tcp
  nfs:
    server: nfs.internal.1337.pet
    path: /export/nvme/monitoring/alertmanager
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: o11y-grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
    - nolock
    - hard
    - tcp
  nfs:
    server: nfs.internal.1337.pet
    path: /export/nvme/monitoring/grafana
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: o11y-victoria-logs
spec:
  capacity:
    storage: 60Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.2
    - nolock
    - hard
    - tcp
  nfs:
    server: nfs.internal.1337.pet
    path: /export/nvme/monitoring/victoria-logs
