---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-nvme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: o11y-alertmanager
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-nvme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: o11y-grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-logs-nvme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi
  volumeName: o11y-victoria-logs
