---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-backup
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: restic-backup-secret
    template:
      data:
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        RCLONE_CONFIG: "{{ .RCLONE_CONFIG }}"
  dataFrom:
    - find:
        name: "bfad4d41-8f71-472e-8d12-fa4e379779f1"
