# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: restic-backup-secret
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:g4MR0bVDaQz8KaTDskOprOeXISNTpjZNyNwlW4uL3eTbqBme0Xoeuw==,iv:bPc4B4uaMvPbwOzehCpBf4ZPEzj6T+upsBicSJm9h8w=,tag:UuTeejjkQXxkacHdzIIwyA==,type:str]
    RCLONE_CONFIG: ENC[AES256_GCM,data:lVlnTRL7G02rah2W7wgqArzL/ajkIabz48IzbBI7NVJVaG6NgcW5m5i9L2I311viIzlTGqexrvl4TJit0UGJKOO0GsQwpWRNVfdA8wcL+JksOiug6q2ZUPyAqRS9aElR1iUX9eBFCUM+kFINt+hzAUnfRMGFMkw9iIGBEsjOSTwgKcXEFx7k9W7PDjLug8b3sMUAL7kbzb2odDbWhfbdK2+xX+abHJahIsdNRT/XDy4wk2z/toZvE459nr/pQciAr88XQeHc3CJOLqrSi9Zwt7E9k90gOwzJSnbkVeZ82+ykDq1gcNXEYBMa4d7X5K2gbUHZhH6xpHIGQYqws5RQ85sohgN7m6HXNyw5L79Yw9zSKuwAYMfwSOeR1Q6KfR6L+iGJ3wIEEXhsKNN3oFfaxDBS/S9ZXXUFEkNgnTXR4XH302i0MZ9RUFrOURT6prz5wenlEZo5QY75FAWHr26HMS813bTKuKITdtaIJS3jkm3vyeKp4vlGE5n1sKJzR3gVl2R9SLxWP01dBbdOkefjbk7uy6opXnT/9gZRuqGOqxXObA1aNJRa4wRu9zE5nmhR11WkIYf89/XGo1S0wTn1ROoe6rByyLVGwAXYex4LJGuaGPNwh+mJN8nzNg3LUau8fPxtfUgoTbzir0P7iIQqid0XGaIw7vgFODdz90/2P9gSg3DFQWCP2dtnwU3GNvPxRzmj/Qk+hpetSEkLqSVB0wucyhVXA54Fj/JrIPHe8gXqnYHR+gS9rp3ZXOxsShHIzBHkGxvKN3/4s//i2tn1kh4Xc9BIu5PFT+9m3a5Uhs120RY1BWysq+EhbeqT+yah1Wp+/6onywOSqbHYNnwSTI0FRLs6gf4zGBGrxLakritOjJ27Ss0ruzN3VtfgT5ktT+sBpucmKHpr7Oe+KujAjCfHPbnkGLnIk/Gqc4iAaJzcBSz+EMmjbVhvlWy0RyC7FoajTL/2uvSRegMTdmc84K724Hvmxb2/7U80qUsidqmUwASUb+Kqz4/gxG8dPsYWi7rRWtobWvFRXGLvQAhoT0Hssu6fopgXbgHEoIqEd2pG+m3+jeh9RcCWRaGtK3vA4vfMXdy2kcTHjwfUuM8YqhnedS8OhgkQFzcTlwsVFLu4lCqV2XC19iF5YYUiUDVpV9AeUhwxuxpxZ7+0D/BuBMDHB8nClcrXcKmc4D5llPrkOgUn,iv:JSv53wGeQJYUWwN10Fu1XGjWGrUR5gs+JQUqlJtEJFs=,tag:lnV4loCQNB8f0DT+fH14mA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWTFBRmczenRKMmxmdERm
            ZHdNUFBYM2RDL25kRkZmNkE5NlRkc2pVWVVFClgrSFlTTE16Rk1HdyszL1VOWUVh
            M2pYMTJjR3ZKTUZsMzExQUhVdGJwK0UKLS0tIDI1L2N6TVZZWW5haHplZk9TK3Ir
            QWE2MmpqcDhKZ1gxWmg5T1hyY2YyaUEK+rmczX2d7HDFAqJfsbcJKhAjk2v5jMls
            SzpyNx7lpuo8prP4w8/M83ig7Q35MvhdZpUpAkv/ddtYI8ty1F0ldQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:rUUG+BaqnBzm2ER/zuDHqCicZoZe6YbevoUOtw1meUnBnUtsTCYtbCnD5M3o8/WLvsNklNXmdp7FP44PdTSYRAG749L0Ft00RJkvLfymLEPS6Hk9Gc9lJ+BnuXS2MBkHgrHdr9eUbsSDCV1vGpR6FLBGTTwHak42r0FOVbz7nl8=,iv:oD/JVav4P/YuD718ormb/QLfALMuhWisLoUwAo/Lq0A=,tag:I57pO3mdJd+wvfbQSxRl2Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
