# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:6Cy+QeZQkGLwGRbJIahako/ESHZNVvvfghQrZ+JgLEg=,iv:08RDbmlvaFJFD8YZKWxYwfzXL5JvLY71Y8N2d+A47lw=,tag:LYSoLYN6ZCVq5SfhyiD4/w==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:m0in/cDOzUDt9/tBn9SkBMpS+gD/0DLYXRN4qpUIQP6GOMu44ny2XJKJ4g==,iv:9YUKb/RYZx3B+Y9A7rHWaQDzGRpYNqtRaGd5DRMFa3A=,tag:UekwUlyYFhnJsNDpeVo0Tw==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:HCh2tfQ=,iv:Cc3A0mMc5yIYODne83r/lXyCSwX+rhl3aMsWKx86gGE=,tag:0PbBvdGlHMSbG/1YPJJTuw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZXEbNXzoPcvJsduUjaCK6WoSl77+pw==,iv:QsdQjUuL8mHRPtJCFmY5R7ulNZz6LGCwE4pXgnhP1Jw=,tag:DAkAmCxw9cGbQJY/CFlh2A==,type:str]
    PAPERLESS_FILENAME_FORMAT: ENC[AES256_GCM,data:f1ITiAMOz1DTTDlQ02/7sR9c3WnjfoMZMJj0/S6J/+vJiIEeG2z4LpSDsBuIRfzTA64=,iv:csYvsBRoB7duO5AjYsElIozaN6ZaScT9vpQ7kO2mjNc=,tag:DRcyQA94sDDfcgVbmo+rug==,type:str]
    #ENC[AES256_GCM,data:oKzXVkCpRpJiqfmtyRc0WbWVv8pzzjVAP1OecLJqOeCv0cKh2X7JtFTazH146sUy0i8DPS5iufMcOvaTDBd/EJcgyxinCVCJHTSjqU3PpKWf,iv:eChwwo506ub3VwMUd8ezgRKP3hYXp0WWroroItVv1Mk=,tag:+FFIpvmiUVCGHkCi+K9EKQ==,type:comment]
    #ENC[AES256_GCM,data:eXGoca+n6zrWxdeCiFMBbGPF1fd89e94Cp6lpVWPlYDzHPQ4zzpU/14Msg3FYOGbSBxpY6h4Tppmcx7PKyFbeP7HJgEjzCMr8gc1wU522g93,iv:kEc7LTu5UU3A52Z+HA/+Rr6jztyVbmhSUUNTCNil1bs=,tag:R0QKgmPqV7V+CQt00nzJTw==,type:comment]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:fjerlojKbHhaXXDHCfbccXVHUVpIMSks4rkQ0AYLhU1ofHeWZoCwag4TQ/LbILImK8M/EPzg5p+MfB8hbQBz/BbZHwjr/Z5/NCW2mbi6h/jxlCxmY5+iN55iS3V2075bI/ouWPOmPlM5z8xJo/U08eMf0IyRnXI394apV1SuQX6qKktzefRtVK+kDe418mAGk9SCzRoLoZ0zef7val0RpBLVjuvszIQaYoF2F+zEXXAqz35goTm9KoNfaXEDNYtYDpAJg2AbCQN/4FS4Kt/ZKnRKn0Z6bBe365OxgDt+OCuaBxt+OHXf51YZFmOkMchlJ+VxqmgNYt1QiQlW6y3A3eSgPhw4puQVp8SCAEQM,iv:TOt6M6aqV2gpWVDNkPkszboAAgBH/4hleV9vkynBHgo=,tag:p9DYEbh/wi7H+2SrS9HHgg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreEhZQXZxNkJ0aHRJUElR
            OXhmajcxaStpVmFucGk0OGNZbFJFU3NCbTI4CjlVb2l5ODg0a1FUWnh5cjNEUk0w
            bkRjSTVSSjJldmFjL3F5NG1QQUtXQVkKLS0tIHRaQTdscWh5R004NkdScXExdXQ2
            YjMyeDZ3RzArQ3ZUTzg0SVZxZ2J5SmsKC9k8GcpWxLCRjy24/nxRm6EnHLRgnICs
            CSjRpai62OEQNaNmltAwtTYK/AKArUdJwJfe/tPu1z2iWD3VHgLGFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T17:37:19Z"
    mac: ENC[AES256_GCM,data:nmEhLV+g2a9TawvQ/USa6lwb4ESMaUyuYV68ptF0wGpWsx2nNIoHXCr4hR9AyjwFpbc9XdDS38L8kDq5M0X0JgzGEzZ0DQZLRN3wy96iSXyEguNxIkE8PUgK6/4GRmJKL6lXzXau3bgKWhwPrkFyfBuu8J/qNvJ3XfbFTjGYA9s=,iv:S+y81AOa35y/6qgCJZHtaajc/zPiBw5zqUxQF1iURUU=,tag:acuI/5X52emoQ4yPPBnK8A==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
