# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:7TfHxEKnBqV23SEI5ei1dQli6Lzwfa/ZidtpkRcCljk=,iv:0kHl8mMKgOi2aIiSGJQYRlwsJDXIhPfx4Y1Pr7WskAc=,tag:IIxFCwZDkNYmAoHEBXAvYA==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:egM0dmVOa3Qya4357pRx9NSs8lR0odyKcME4ZQG4LQQWsUOF8q89i+crjA==,iv:11v0hvoLsbDznyXpsx2zaPVxTCXeTh1x0U55blPAUsg=,tag:5Ymk5MmoBhV5v3oJC7aEIw==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:oSu/v5I=,iv:T4cF+XCzbugHaef4uL0akLpXLLPHArEky+p7DpUWne8=,tag:PWwUeZlfYc9FtEoEQYhEOw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:W/GejNrcgJEz4N3zGFTkAtIooKWNhQ==,iv:CqmP655+eCKJnbYWTXGTegPClY8a2h0YoHzO0ZWQG48=,tag:pko+qvjEX5ZAp849OQBbyQ==,type:str]
    #ENC[AES256_GCM,data:vyCRRIjNozHLSoTFFO3//MMGAb0YjrfXSiZZbGQLRujIEhu4/QBFk9BvQdq6tn98IlY/eR1nAdoSR0ObHHyE1UupPp5pOh1lzkgjRJWCDL9e,iv:kBSvLdo7ZLZEEj+1vQ6V5d/DBmx/rFQ7taFA2nbGykM=,tag:WUB1nadzGQSmAyABeeBn9A==,type:comment]
    #ENC[AES256_GCM,data:QQrb4fhFdQ9o0UDI5u9V5+EmQChdhAxspPEpBh4toX46iWqD3U6qmFa+QHADb2S8uBPPR8YTEHfFz4s/tfn6FV7Og2eP412/7sU4Mnzk332G,iv:B59Pj195y/hwZ8udf4AU60+PrpZycKpNYBOrfFusF7g=,tag:Lgnc6yCETLVnlFil2hHN2Q==,type:comment]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:ZRU1ZJPhBB6n74FQw8ss2ZQdnyrWboDGJ19a1J5DqxOcu2dslJgBHq4C43OnDsoW5f4hX2XINI0pKrl630P+oCH2hnMtR9bJCHDsJbNvtk1tNJyQJHw8m32jtr67eKDxbYI+WXjCK+J2aa1tRvBg+lTCYjevwK0N60qBYRYCGW0v0G0vQcQQwrAKc/GAsalaKqj0b58reLFwBnlvICXeKqmfqu3ZbpQXUpuVZBlR2bIaZW/k/kxkIgbFdIkyVBiKZCjBnqyJGS1MYKvHUb4XvmCVFJAn+drXylyLdrpPB8NDq3NLX1C9xvmOIPs8P7nOzIk80GWkGuB/sdTw/MkZ3JoZZ3s7XdQbluDDEeoO,iv:t+syqurSlu7aLG/RoGIJZ7lTtTzsmSUcr5QE1C21Hco=,tag:jcS4QV6h1NuwZDceShO2Dw==,type:str]
    PAPERLESS_FILENAME_FORMAT: ENC[AES256_GCM,data:KvZnkeFotI1s5lB8EWJQzZGx8k/MZOWbeyrmGaxffqMlB9T51fg63vQSz3WyWHc7gHA=,iv:xvo/WRHnYkGjw4HsM+yqwzxmwph9dGIvRWvp58wPwdQ=,tag:jFyfRB1zoCYnXKB1APoPlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRDBmVzZoaVNDbENzT2kw
            QXNrNmtKRlBMVTdGZXd5VElkeFkwb1NkbFVJCkkrYjQ1aVQrTWwyaGJPUG9aMjNT
            MXI3NTI3cUtqKytwTFhnNnNJaE9DTVUKLS0tIDRZd1hxKzhGMVZ0bk5CYWxOZFpC
            UmkweE5xUktFdkUzL2w3MEV1NzFRYVUKWBwtunU0Ol31Ct7E9Z0ZsEohlmshodie
            O9XmjT6rmWw8UrdlmaPZQAyVCcDiRvPRDvRasW+yeR5BHUoOYapGhA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T17:32:42Z"
    mac: ENC[AES256_GCM,data:rm55FgHjKC7eOR6yoDDStoolshOGB3y8k0RvDnwkO+Xbv+tgoCBsSiKvgv+EBhrJ4BgAUn3SMax7O5yt+Z1Hh9fIfk8fJOev/dsGp9wSSgMfEkRX1Ij5JwRmbUamv96UtrboRN2R04iNbBRNUYrcnEXRrOXuRsC3TBsPv0mUKJ0=,iv:cSEKEJT9EzGANW0RMH+yp6BHRDsBYHDBbaSTc0QkOHE=,tag:/yex+ePXBAm9UveDVQtQJg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
