# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
type: Opaque
stringData:
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:JzMEbu2xaM5D6wXZs8aBxl2jqJ9I9Y9pXl0Ob0LocaQ=,iv:9mqRmADQViLMfyBRR9xazKFjBpI8Qz2SIFEt/pTxQBs=,tag:VCYhDRGBrwo9SDfthlRTxQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:a4xzTodvFfs4ePLD3h4NClCLvlYjEMH0UExQR7glJaTycwzuGoYAPyX5pA==,iv:8Z3JzJvT1tukukW+mIPWq0RfYyge8q6B+93pZJaLUII=,tag:mKmJdPRCC62fVDfeLQb7nQ==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:nX783Uc=,iv:sTMBmJ13QtW3GHeDkZa4SNfYuQdArRvh2B5IQ90XDiw=,tag:SY290zz3ZWPouIL+1niLXg==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:UJlSF+jNN3b6q0x/SgJ3k1IvVQwaAA==,iv:2sWbNwU1QfrnLQ2ubDjMP9Uy9FCOK7gaEd+Hcsqayr0=,tag:F0/Sym9Y2vTcXggsKXQQIg==,type:str]
    #ENC[AES256_GCM,data:flC0+l/4+D5F3RJPrCCQkd4TgKBwQfmF+dgottIHTR98g1jyba0PPzOYnbYl9107W3/tl+pyDPx7NI2zviY2zZ0AOydu/CQ6vr/Ix/LJHDGB,iv:qtHFti37dfUMDA1KGDsBzDtGObxamk8RptUE9vBLpWA=,tag:qqX4OHMY42WtlN2R6c1h9g==,type:comment]
    #ENC[AES256_GCM,data:Ud4rYEzuOPyXeuZzShfRLeqPEMvEcKQCdhFxevN5uUkIHB4i1I4QxhK/mhy9DejsRuUrX2GnbAnudvGYZSLTQC7PfqIPlvy2yYUKOlKV4Uzd,iv:rdAy6zWAXdg88RMjTdukgCnRqKrKFWucvstnoc6ThPM=,tag:gyLLKFU1WeuzBIKsR/VIUw==,type:comment]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:KbCMMd4Me8yp+9XB2rpmbm3IRcJs1TNCmtXLavdr9VTLR3yPy7dKt+l0lPenRIrf6SPLNA87hC5F9n51PWva7Hy0iyOlrYxJhnSSKoRQ1/Sy7aOpmhuF4q0HUrC5S/T37Ybw5pzH25laPDR6hm1hd82jAqzj1fYbY5VUwcV7L+wL+j45lhUjhOMmlWJZYtU+NnnKwLpwVkkl7EY24mqiEngWCHO2b3YQVqB/8fucyiIfEIl/h2IdXqRWjLjfkqgRmKUoJPHHiwPv9aIIKI1vc+sTqasR0AUdXA9NK2ADa9iNn8adpM7rwNCPBIbRiqdo0RtEj1yIfbv79u0coO7sFyPSJCL1sToC0H6npTtt,iv:C2KQpHXwIr1ZFmbDRIBkzE1ubFiSTdkfRRyeEyyCaT0=,tag:jDeTWFTfhJTlw9Cvy27irQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXenBNRklhajNyaGJnTlhE
            VFlIZEFWcHBVb0lQUHF1WHZNUkxzaVY3NFJ3CjNXTHBldlZ1KzNQcTVUZUthWGt5
            cHh3ZXJmRko1WkFNdG5NR29GTjgzRkkKLS0tIGorTnhRa3QvK3lOVjZWUmhnUTF2
            TWs0eUU2LzhvMXdyanRJREsrdTZjajQKny6fpHKzSqMaf4AGwUF5Gj8RIuou5/hS
            bR7U0BDx4wtFDhQRiOMxpul7IneaszYuRwZVGiP5M7pDuOzoS/L0FQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T17:22:40Z"
    mac: ENC[AES256_GCM,data:FHOsLPxWTBCo/x74iuSal8v2Tx3hQMP/fG29fNz6GQNkvl7JiGEO25zWeXRv+ciUj60RDniXuafbnvzaSk7VpmHY8WkWFgVaaEYxNLU3sbhTaq063PbOt0aBzSq92/e4oXFEfwBkOkYCQYn9FpooLHeC4qj0p+QL687PpG0pTwU=,iv:t3ivR7eiHPEPeexPofWaxh2LgEAon7b8iwrz7l6nekQ=,tag:MZqOaSRS7EGMfDNncP4mPw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
