---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.1/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: penpot
spec:
  friendlyName: Penpot
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.1/dist/schemas/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: penpot
spec:
  name: Penpot
  clientID: penpot
  # Penpot OIDC client does not send PKCE code_challenge.
  pkceEnabled: false
  skipConsent: true
  callbackUrls:
    - https://penpot.1337.pet/api/auth/oidc/callback
  logo:
    nameOverride: penpot
  allowedUserGroups:
    - name: penpot
  secret:
    name: penpot-oidc-credentials
    keys:
      clientID: client_id
      clientSecret: client_secret
      issuerUrl: issuer_url
      discoveryUrl: discovery_url
