# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: penpot-secret
type: Opaque
stringData:
    api-secret-key: ENC[AES256_GCM,data:ewdgqcz9oQKtAc/AGtJXMkGnMKh6WQ5wqGs3ohE4UNV+C2rTCqs8mZeKTvcfHFIM9H+n9JTLmTkuAvMQh1bX4LvXR+Mw+kjMrrgvrvRgZW8tv6xP1Xk=,iv:krm+Kn8bGBwCHo7SMlCMF6TwjoPCwdGqEWjlpkGxk0E=,tag:/YKOCdeZCn9VtNt77MHPgw==,type:str]
    s3-access-key-id: ENC[AES256_GCM,data:UaFmsA==,iv:5/AvO6kJphFl1md0Uehztozule0JnVMT5n/d1a6wSPI=,tag:V0w/U/+2JsuSy7fo6GLlzQ==,type:str]
    s3-secret-access-key: ENC[AES256_GCM,data:UY7P+s11J8hlDGT9N/uWHv5raWM1hXccQr1on7wV9Sx97ofkBVwFLg==,iv:XZLNMSGitKnvAPBZ57aIj1okWRRquxLG3bYSlZ8BXZk=,tag:mAfGGP1h1mRUzrDUj/V4zw==,type:str]
    db-password: ENC[AES256_GCM,data:c+GYLAlEdA9bvFCmYf0cBJDVPfIottdvcJrqKC75e/c=,iv:BLRFqhhj4JjIR4rlDeYyaH8oZH62iI6BbjcSPz8czx4=,tag:I6pHG/Q0X/JYvMQaT8kOgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRFRqQUczMUtsQk9Ycm5q
            ZEtjTExIN3BVcVlKWFU2aEhZdmY3N3lzbzBRCndBOU9GS1dDUmppVENQNkVzd0Rt
            aUVGcGxZRXZrY3p5dlFVSkU4L1dla1EKLS0tIGswOFkzYmUwL1dDeHBHOXVmczFk
            ZHUvK2RrUVRrdXVKUCtZZ09id2E3SGcKeZ2Ppw0Mx8xrQ6QHMlux+kFztJ3/etHT
            4lMBLcNNp3Hnj1yEngF9a1lr/eLytINODu5gSY3rDnkLsG40k3ybtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T19:26:49Z"
    mac: ENC[AES256_GCM,data:5fgYeu3X+8tOrDmPopNPvMOKudW+Mo6sLc/+gB+jy9UD+itcm2Rgx0Gb5pQTNE04ZtieLSzG2wiRFoFqxSKJI2QENrR+hIk7SPBDBhyF+uxBNLmCiiFXwrYLE0LGMcV8OFHG4HfeM63N6d1UUYYgvXB7Jwj5BpbraygOP3GYHp4=,iv:nxPDXPPGpbYjpdjJ9/bnhGf5UIgDonpy4wnh5uFA6Nc=,tag:T+zAwmSJN96Lueg/dzHQdw==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
