# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: timemachine-secret
type: Opaque
stringData:
    PASSWORD: ENC[AES256_GCM,data:yIgyKSR3VEnDDXJa4JoIqGTWJn+lWKwR,iv:yBzvuQ3X49e5k/udbltm4Pg/1wwC040zNmM94OnAONw=,tag:J7+B5xwbl2RFg13fVH0dWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNSsySWdnaUVaTzVVVjMz
            Rm5uQzl4OEJCay9ISzBlNzNXbS9mK1pTS1J3CmtBVnc1V2RZOW5adHRMYzZBRmp1
            OUVqbUNteGVGWHJoWWhwQ3pFUjVQSXMKLS0tIHFKMmlmeVRmam0ycmxnQkVocy8x
            MlpXQ3o5RVkzNnRNR2piUWVEZUp3VWcKYolFOPDllvSJ4aFWUdIz7tK3qDRZKE25
            7vhEFrqoJWpDMr1kdVtPAT5we4KVSK6WEI57sh7W2RCAuMHj8X8psw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:48:36Z"
    mac: ENC[AES256_GCM,data:XQ3aj1lyZ0TQQCwEIJJ+A/9xnhcaSZ1kHiatOFR0RbQL15Zg1MNzcrUws50zl/teBOonoOtl/FXnmIrePv6manQYbNaeAoZKxc0WI3DKJO+7/+79WxJol8HMNP085UamT7+VcPN5yql9R7y71YeOxNbg45o12x/lCfH+D3JNoEg=,iv:3aMoPGUVdROC4DTY4Sfe7YxAoPIQvoCQaDCfvPpsIYM=,tag:UKGJCTvOh5j999f+48X/Rg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
