---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-system
  - ./backup
  - ./cert-manager
  - ./databases
  - ./default
  - ./flux-system
  - ./kopiur-system
  - ./kube-system
  - ./media
  - ./network
  - ./o11y
  - ./storage
  - ./system-upgrade
