---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seaweedfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: seaweedfs-s3-secret
    template:
      data:
        SEAWEEDFS_S3_ACCESS_KEY: cnpg
        SEAWEEDFS_S3_SECRET_KEY: "{{ .SEAWEEDFS_S3_SECRET_KEY }}"
  dataFrom:
    - find:
        name: "5d9cd59b-1e63-4a49-9a49-fdc0370fdf2c"
