# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-secret
type: Opaque
stringData:
    SEAWEEDFS_S3_ACCESS_KEY: ENC[AES256_GCM,data:gF677A==,iv:uZrZzWJ3y6KDkIUI0Z+0ecEbXXvK+m+c1eZ6MgvgMw8=,tag:w+aMT7V+kKjo5wHXcBhsiQ==,type:str]
    SEAWEEDFS_S3_SECRET_KEY: ENC[AES256_GCM,data:oh3RzH28j2Pq/PBxKsSWOkRrhO3QL4fPymo5eYzrQ8gFS8xapIqExw==,iv:wW4R+Byw06PHQuSk2rwgru+Fxbri1XzbWCsJg44rJbM=,tag:MzPFG4IDY+nKUccxLtqaTQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBha0FqWGF4RS9lMTRReC9X
            ZGFGbHhZSm5haXhqUHozYmFwNFphbFJOaXdBCmxHMTlrOEp6cUpuN3pVa21BMFh3
            SjA1bW9idFFIbk1GZ3ZqNFVuWnIzdjAKLS0tIDNhSUwzcWIvbjg5dmNBQ1JCcWxX
            YjUzMDc3WGhzNnJWU042RDIyS08zNjAKROMCq6qpvDNxgnw0UT/dHVoz/gy2zRyS
            RC33oKCpRFtxRMovqB6XppNkb6Pzf7aKJeQasFwEy2tGhYPdEE2/uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:4QsOLZbfNeVZ7xipatK7fXcgMiNGeTL+zdVloanbRfo3T9MCWMOo3ibs62D9cMSrdRgk3YVsmOvg2NGifxZdwd43E+wefgc8QaCBnn0CnQKvOgI0PFl2rVzHhdBfffaFKolLmDnw1Qu0VAigRB3Wz26n9d0BAenrmLh3Tl7OAcE=,iv:ZsGAKhTVLC/qVVxVgy3aYBH90XBvQwvjJvAc8W0xSDU=,tag:2GaiVQ64/ZFvIy9jDhCGBA==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
