---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.1/dist/schemas/pocketidusergroup_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: linkwarden
spec:
  friendlyName: Linkwarden
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/aclerici38/pocket-id-operator/v0.11.1/dist/schemas/pocketidoidcclient_v1alpha1.json
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: linkwarden
spec:
  name: Linkwarden
  clientID: linkwarden
  pkceEnabled: true
  skipConsent: true
  callbackUrls:
    - https://linkwarden.1337.pet/api/v1/auth/callback/oidc
  logo:
    nameOverride: linkwarden
  allowedUserGroups:
    - name: linkwarden
  secret:
    name: linkwarden-oidc-credentials
    keys:
      clientID: client_id
      clientSecret: client_secret
      issuerUrl: issuer_url
      discoveryUrl: discovery_url
