# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secret
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:M1GirCKv2McPMV9gr61Z7XTOyGgtZoEDVTC6nWIqx+ob5ZzmerdoAukNJ15FaqtiYJcOAN78DOPECHjjyAT5GQ==,iv:ysqQFZlZMd0/TJU2SkuxAKgqr1jYyxhAtVlfuoRdSTI=,tag:epU3f4/bFeNV87LBW7XhXg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:+k90i8n2QGYL6hlTiR3nDnn+C0cjmss8xXP/JLcBNs9jH2TVGARVvk280TpG89rFmhbpwF6FJnkVXhzuywAQzgYePkkUG3LjZHsegXUqW8zblDr2B4RnZqh3Gx35Li+op5MJRwgonDufcMJp5Uc1TGGlALmEME78SK+dZkgvZA==,iv:htvWt7L+aMhyHuSKiJi6MJn/hxLq1+NW2P4ewaTyRZw=,tag:z5cAdoOm4FWL3Ge/A8g+Qw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:abfvIG1yQwxbAuf2SCw0V96O2Hc20zEK4tYKRFytKjA=,iv:Ztezb3yS6TCj+l7vDxfuBj9oss2dteZlo/P5hS/Utxo=,tag:7u5jE6rwlvQDhOMNV8+khA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:E7yAG//UKpPugnZLVBUauVGJdMlh8C25MAN5TvKiOli17GZ3u5sYKM84Mzf+KLDIWcT4spJ/kVJmX1U85w8dGw==,iv:k/eFuIDRXOREtuzw6cO72qDQgj1GS+ClseBJK1idJbc=,tag:0mytTaFoPfPtQgQ0/FQj+w==,type:str]
    SPACES_KEY: ENC[AES256_GCM,data:msmQCA==,iv:RrprObGc4hsQyQrZiV0fjRhN8KGi9ABza5M5zJDMNSk=,tag:Y6SAnfNUNpnQOWtYHVMrdg==,type:str]
    SPACES_SECRET: ENC[AES256_GCM,data:jfOhwVBOOZBuBmrWXpguf76ZfV5ZTmH0lrpYN5q5wtQKcUL/Ci9EHQ==,iv:+dr2Ha3ogNu2x98G9Kajvxr02KcPvv7yJa5EXYDIUtA=,tag:bH8Ra/kyrYa17E5ZAO2cSg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySGZXTTZRWTRvaWhFb1hH
            YkFHbVJiUVkrVG1ZRVo3M2gzamhVNndvK1g0CmpBZXR0K0d5RTVPY2xMNnhXbHpz
            UW1sUWdYNkNkSmdGUVlUck5IWkdWdWsKLS0tIDdwRHlnQS9oN2lVUnYrbVg5ZWFG
            dkNPZEZGV3d3RmVmcDFZUGd3N1h5dWsKpAYOsvPSpxVruoyJ6KOEpBkh2+eca+Ja
            rxaRoZE9rx2J17knOxOYfZYuNe6PSz3aHnjcqxwfrqk2zBWJyhlfEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T18:18:42Z"
    mac: ENC[AES256_GCM,data:S8e2qqThyYivKERzOvxEAYy0Ra/+DV9ye0TQgPbqTkZBvPT0ACgxfFS1h/m/xMjk0eL/Xbl1HeWNPfuN/toi8iV6HzV/BHMoPgPruZu9e0/3/6m3MJl3mCc8FoUgMnBJTQYOHmI980haTD1+J2SUkVz6cQ0Lu9n1uAu5XgER3QA=,iv:i1U/grWRJzsGaapYkDVMeK2AB0s3EcTjHtsq+IMkw8c=,tag:CYpNKBlV4qFjPJ7r9xPnVg==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
