# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kestra-proxy-secret
type: Opaque
stringData:
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:XaBIu2wuvOd1nG6D/M+SgVCQX4J+Fb+CBingIKkg7qk=,iv:D5qRsg/y/JDc+TJRrIJFMFPHyLN9nq/kW0zJHgnxNPU=,tag:vpFo+/SKLBoKs+P9EGqerg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZlE0dlc0a0lKajlyMk5t
            QXdpUDlreDNGeDVPY2tqTWsydFN6VURoMTFNCkxJU0tSWk4vTHNsaW45K1ZyWUla
            N3IwbnpGQnJKNkhsTlhKUUFoekQvWjgKLS0tIFFxZklJMGlsT0xTVjZUZE5LYjA5
            b1RYVnIwTUNianJxRkFQVFpHS3ZOZlEKtDkwqDMs3uNHpZtwDm6Ypn4+bl+uMij4
            5me5B0yZRGpm379vyc2Lu948xgJ9yADYjbFd4tO85HANxhA+UP+/GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T19:42:38Z"
    mac: ENC[AES256_GCM,data:pbUq47bVW81ntCzuhZ+0/TuV7pMy350xnfhwuu2SyXeZUhSdFC54Z6Gdm/5TtOvFFXjHs3Da6HC1lZderU7Y8WY9DWj+0Pc2MczzslUWHgPMIxxyC25pEYE5DmTKCSUSve8JrPDWx8cDPqjjDQUtNlSFiKu2REx5gyda8uCOfZc=,iv:onqPMVE68+Nm9zhBjtHT7QYfxbFRR7u527UEZVb/vYo=,tag:fFxfA64Cr8Qs+wjHPMXP0g==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
