---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vaultwarden
  target:
    name: grafana-admin-password-secret
  dataFrom:
    - find:
        name:
          regexp: "781453e7-ead3-4b6b-893e-1a1f2c85202e"
