# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.34.0/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password-secret
type: Opaque
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:epKtMkFwQeu/Lg/4z/ydDzT2Ky/yZMg9MGaKFBpfdmM=,iv:NkLGHyacz6/AHjdIs6OrjVbKXK+pFd2q/nDYPQaO1CM=,tag:r1kOmUXZRZ4FErVMVNtQoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCR3pnL1E1dFIwNUJlQ1Vj
            U0Znb2JjR2Jac0o0STdoelNETlluZTlTNnhzCi9kWjhUek02bXYyc3R4S2FkYjla
            anV3R3d3WFVNakRoTHVjd3JuM01rVE0KLS0tIG5WT1FTcjVIcHVDUjNyaXJVMkRH
            QmM5ZkFvRVpvMU9GTVdQSzlIY1p0UjQKheQ8pvhPLNavg/Sdtib/ruci7iRofbyb
            adBGVcwTWKlqesF2JD64bswngdOS+j4FBsCNtTAC7PvWIgLL8M64XA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14mr55ap6mywdf7gp0nzfgtfttscpkmzegq79xhq0eqz3s3pn4sjq5gtyuj
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T02:20:26Z"
    mac: ENC[AES256_GCM,data:iISl9AOfyMBMgQrQn3Nsb58psTxbhftCQEi2RqTJiZqACz9P+VwH1LHjYKbH8L7l3R3aqZBVDBc0lJtpadoHs8hNYwX8vZ7NcMgsBhD32xPENZNPGWrOugkjtLnqdILRT4ek7p4/Zbc4m1FxvdqrCIAnKaoy5dRXGkRU7Q0Nt2Q=,iv:BjzFR45iA+4AmFgzaslLFElJF9/kfbXDHrrBE6Drbfs=,tag:IoRSoBUYOND8HCuth14K3Q==,type:str]
    mac_only_encrypted: true
    version: 3.13.2
